const data = {
	name: '人类活动',
	groups: [
		{
			name: '日常用品和概念',
			symbols: [
				{char: "☎", name: "黑电话", ename: "Black Telephone"},
				{char: "☏", name: "白电话", ename: "White Telephone"},
				{char: "☐", name: "投票框", ename: "Ballot Box"},
				{char: "☑", name: "带勾的投票框", ename: "Ballot Box with Check"},
				{char: "☒", name: "带叉的投票框", ename: "Ballot Box with X"},
				{char: "☃", name: "雪人", ename: "Snowman"},
				{char: "⛇", name: "黑雪人", ename: "Black Snowman", tags: ['雪人', '冬天']},
				{char: "⛲", name: "喷泉", ename: "Fountain", tags: ['喷泉', '水']},
				{char: "☠", name: "骷髅和交叉骨", ename: "Skull and Crossbones", tags: ['海盗']},
				{char: "☡", name: "警告标志", ename: "Caution Sign"},
				{char: "☢", name: "放射性标志", ename: "Radioactive Sign", tags: ['辐射']},
				{char: "☣", name: "生物危害标志", ename: "Biohazard Sign", tags: ['生化']}
			]
		},
		{
			name: "经济、货币",
			symbols: [
				{
					char: "$", name: "美元", ename: "Dollar",
					tags: ["货币", "钱", '美国', '加拿大', '澳大利亚', '新加坡', '新西兰', '香港']
				},
				{char: "¢", name: "分", ename: "Cent", tags: ["货币", "钱"]},
				{char: "£", name: "英镑", ename: "Pound", tags: ["货币", "钱", '英国']},
				{char: "¤", name: "货币", ename: "Currency", tags: ["货币", "钱"]},
				{char: "¥", name: "人民币、日元", ename: "Yuan, Yen", tags: ["货币", "钱", '中国', '日本', '元', '円']},
				{char: "֏", name: "亚美尼亚德拉姆", ename: "Armenian Dram", tags: ["货币", "钱"]},
				{char: "؋", name: "阿富汗尼", ename: "Afghani", tags: ["货币", "钱"]},
				{char: "₲", name: "巴拉圭瓜拉尼", ename: "Guarani", tags: ["货币", "钱"]},
				{char: "₵", name: "加纳塞地", ename: "Cedi", tags: ["货币", "钱"]},
				{char: "₸", name: "哈萨克斯坦坚戈", ename: "Tenge", tags: ["货币", "钱"]},
				{char: "₺", name: "土耳其里拉", ename: "Turkish Lira", tags: ["货币", "钱"]},
				{char: "₼", name: "阿塞拜疆马纳特", ename: "Manat", tags: ["货币", "钱"]},
				{char: "₾", name: "格鲁吉亚拉里", ename: "Lari", tags: ["货币", "钱"]},
				{char: "₿", name: "比特币", ename: "Bitcoin", tags: ["货币", "钱"]},
				{char: "€", name: "欧元", ename: "Euro", tags: ["货币", "钱"]},
				{char: "₨", name: "卢比", ename: "Rupee", tags: ["货币", "钱"]},
				{char: "₩", name: "朝鲜元、韩元", ename: "Won", tags: ["货币", "钱"]},
				{char: "₪", name: "以色列新谢克尔", ename: "New Shekel", tags: ["货币", "钱"]},
				{char: "₫", name: "越南盾", ename: "Dong", tags: ["货币", "钱"]},
				{char: "₭", name: "老挝基普", ename: "Kip", tags: ["货币", "钱"]},
				{char: "₮", name: "蒙古图格里克", ename: "Tugrik", tags: ["货币", "钱"]},
				{char: "₥", name: "密尔", ename: "Mill", tags: ["货币", "钱"]},
				{char: "₦", name: "尼日利亚奈拉", ename: "Naira", tags: ["货币", "钱"]},
				{char: "₧", name: "西班牙比塞塔", ename: "Peseta", tags: ["货币", "钱"]},
				{char: "₴", name: "乌克兰格里夫纳", ename: "Hryvnia", tags: ["货币", "钱"]},
				{char: "₹", name: "印度卢比", ename: "Indian Rupee", tags: ["货币", "钱"]},
				{char: "₽", name: "俄罗斯卢布", ename: "Ruble", tags: ["货币", "钱"]}
			]
		},
		{
			name: '建筑',
			symbols: [
				{char: "⛬", name: "历史遗址", ename: "Historic Site", tags: ['遗址', '历史']},
				{char: "⛫", name: "城堡", ename: "Castle", tags: ['城堡', '建筑']}
			]
		},
		{
			name: '饮食',
			symbols: [
				{char: "☕", name: "热饮", ename: "Hot Beverage", tags: ["咖啡"]}
			]
		},
		{
			name: '出行、交通',
			symbols: [
				{char: "☂", name: "雨伞", ename: "Umbrella"},
				{char: "☔", name: "带雨滴的雨伞", ename: "Umbrella with Rain Drops"},
				{char: "⛱", name: "地面雨伞", ename: "Umbrella On Ground", tags: ['雨伞', '地面']},
				{char: "⛺", name: "帐篷", ename: "Tent", tags: ['帐篷', '露营']},
				{char: "⛵", name: "帆船", ename: "Sailboat", tags: []}
			]
		},
		{
			name: '艺术',
			symbols: []
		},
		{
			name: '音乐',
			symbols: [
				{char: "𝅝", name: "全音符", ename: "Whole Note"},
				{char: "𝅗𝅥", name: "二分音符", ename: "Half Note"},
				{char: "♩", name: "四分音符", ename: "Quarter Note"},
				{char: "♪", name: "八分音符", ename: "Eighth Note"},
				{char: "♫", name: "双八分音符", ename: "Beamed Eighth Notes"},
				{char: "♬", name: "十六分音符", ename: "Beamed Sixteenth Notes"},
				{char: "♭", name: "降号", ename: "Music Flat Sign"},
				{char: "♮", name: "本位号", ename: "Music Natural Sign"},
				{char: "♯", name: "升号", ename: "Music Sharp Sign"},
				{char: "𝄀", name: "单竖线", ename: "Musical Symbol Single Barline"},
				{char: "𝄁", name: "双竖线", ename: "Musical Symbol Double Barline"},
				{char: "𝄂", name: "终止线", ename: "Musical Symbol Final Barline"},
				{char: "𝄃", name: "反向终止线", ename: "Musical Symbol Reverse Final Barline"},
				{char: "𝄄", name: "虚线小节线", ename: "Musical Symbol Dashed Barline"},
				{char: "𝄅", name: "短小节线", ename: "Musical Symbol Short Barline"},
				{char: "𝄆", name: "左重复线", ename: "Musical Symbol Left Repeat Sign"},
				{char: "𝄇", name: "右重复线", ename: "Musical Symbol Right Repeat Sign"},
				{char: "𝄈", name: "重复点", ename: "Musical Symbol Repeat Dots"},
				{char: "𝄉", name: "从记号处反复", ename: "Musical Symbol Dal Segno"},
				{char: "𝄊", name: "从头反复", ename: "Musical Symbol Da Capo"},
				{char: "𝄋", name: "记号", ename: "Musical Symbol Segno"},
				{char: "𝄌", name: "尾声", ename: "Musical Symbol Coda"},
				{char: "𝄍", name: "重复图样1", ename: "Musical Symbol Repeated Figure-1"},
				{char: "𝄎", name: "重复图样2", ename: "Musical Symbol Repeated Figure-2"},
				{char: "𝄏", name: "重复图样3", ename: "Musical Symbol Repeated Figure-3"},
				{char: "𝄐", name: "延长记号", ename: "Musical Symbol Fermata"},
				{char: "𝄑", name: "下方延长记号", ename: "Musical Symbol Fermata Below"},
				{char: "𝄒", name: "呼吸记号", ename: "Musical Symbol Breath Mark"},
				{char: "𝄓", name: "休止记号", ename: "Musical Symbol Caesura"},
				{char: "𝄔", name: "花括号", ename: "Musical Symbol Brace"},
				{char: "𝄕", name: "方括号", ename: "Musical Symbol Bracket"},
				{char: "𝄖", name: "单线谱", ename: "Musical Symbol One-Line Staff"},
				{char: "𝄗", name: "双线谱", ename: "Musical Symbol Two-Line Staff"},
				{char: "𝄘", name: "三线谱", ename: "Musical Symbol Three-Line Staff"},
				{char: "𝄙", name: "四线谱", ename: "Musical Symbol Four-Line Staff"},
				{char: "𝄚", name: "五线谱", ename: "Musical Symbol Five-Line Staff"},
				{char: "𝄛", name: "六线谱", ename: "Musical Symbol Six-Line Staff"},
				{char: "𝄜", name: "六弦指板", ename: "Musical Symbol Six-String Fretboard"},
				{char: "𝄝", name: "四弦指板", ename: "Musical Symbol Four-String Fretboard"},
				{char: "𝄞", name: "G谱号", ename: "Musical Symbol G Clef"},
				{char: "𝄟", name: "G谱号高八度", ename: "Musical Symbol G Clef Ottava Alta"},
				{char: "𝄠", name: "G谱号低八度", ename: "Musical Symbol G Clef Ottava Bassa"},
				{char: "𝄡", name: "C谱号", ename: "Musical Symbol C Clef"},
				{char: "𝄢", name: "F谱号", ename: "Musical Symbol F Clef"},
				{char: "𝄣", name: "F谱号高八度", ename: "Musical Symbol F Clef Ottava Alta"},
				{char: "𝄤", name: "F谱号低八度", ename: "Musical Symbol F Clef Ottava Bassa"},
				{char: "𝄥", name: "打击乐谱号1", ename: "Musical Symbol Drum Clef-1"},
				{char: "𝄦", name: "打击乐谱号2", ename: "Musical Symbol Drum Clef-2"},
				{char: "𝄩", name: "多小节休止符", ename: "Musical Symbol Multiple Measure Rest"},
				{char: "𝄪", name: "重升号", ename: "Musical Symbol Double Sharp"},
				{char: "𝄫", name: "重降号", ename: "Musical Symbol Double Flat"},
				{char: "𝄬", name: "降半音号", ename: "Musical Symbol Flat Up"},
				{char: "𝄭", name: "升半音号", ename: "Musical Symbol Flat Down"},
				{char: "𝄮", name: "四分之一音升号", ename: "Musical Symbol Quarter Tone Sharp"},
				{char: "𝄯", name: "四分之一音降号", ename: "Musical Symbol Quarter Tone Flat"},
				{char: "𝅅", name: "长休止符", ename: "Musical Symbol Longa Rest"},
				{char: "𝅆", name: "双全休止符", ename: "Musical Symbol Breve Rest"},
				{char: "𝅇", name: "全休止符", ename: "Musical Symbol Whole Rest"},
				{char: "𝅈", name: "二分休止符", ename: "Musical Symbol Half Rest"},
				{char: "𝅉", name: "四分休止符", ename: "Musical Symbol Quarter Rest"},
				{char: "𝅊", name: "八分休止符", ename: "Musical Symbol Eighth Rest"},
				{char: "𝅋", name: "十六分休止符", ename: "Musical Symbol Sixteenth Rest"},
				{char: "𝅌", name: "三十二分休止符", ename: "Musical Symbol Thirty-Second Rest"},
				{char: "𝅍", name: "六十四分休止符", ename: "Musical Symbol Sixty-Fourth Rest"},
				{char: "𝅎", name: "一百二十八分休止符", ename: "Musical Symbol One-Hundred-Twenty-Eighth Rest"},
				{char: "𝅏", name: "二百五十六分休止符", ename: "Musical Symbol Two-Hundred-Fifty-Sixth Rest"},
				{char: "𝅐", name: "五百一十二分休止符", ename: "Musical Symbol Five-Hundred-Twelfth Rest"},
				{char: "𝅑", name: "一千零二十四分休止符", ename: "Musical Symbol One-Thousand-Twenty-Fourth Rest"},
				{char: "𝅒", name: "长音符", ename: "Musical Symbol Longa Note"},
				{char: "𝅓", name: "双全音符", ename: "Musical Symbol Breve Note"},
				{char: "𝅔", name: "有符干的双全音符", ename: "Musical Symbol Breve Note With Stem"},
				{char: "𝅕", name: "带斜线的双全音符", ename: "Musical Symbol Breve Note With Slashed Stem"},
				{
					char: "𝅖",
					name: "带斜线和符干的双全音符",
					ename: "Musical Symbol Breve Note With Slashed Stem and Flag"
				},
				{char: "𝅗", name: "黑双全音符", ename: "Musical Symbol Black Breve Note"},
				{char: "𝅘", name: "带符干的黑双全音符", ename: "Musical Symbol Black Breve Note With Stem"},
				{
					char: "𝅙",
					name: "带斜线和符干的黑双全音符",
					ename: "Musical Symbol Black Breve Note With Slashed Stem and Flag"
				},
				{char: "𝅚", name: "全音符", ename: "Musical Symbol Whole Note"},
				{char: "𝅛", name: "带符干的全音符", ename: "Musical Symbol Whole Note With Stem"},
				{char: "𝅜", name: "带斜线和符干的全音符", ename: "Musical Symbol Whole Note With Slashed Stem and Flag"},
				{char: "𝅝", name: "空心二分音符", ename: "Musical Symbol Void Half Note"},
				{char: "𝅗𝅥", name: "二分音符", ename: "Musical Symbol Half Note"},
				{char: "𝅘𝅥", name: "带斜线和符干的二分音符", ename: "Musical Symbol Half Note With Slashed Stem and Flag"},
				{char: "𝅘𝅥𝅮", name: "四分音符", ename: "Musical Symbol Quarter Note"},
				{
					char: "𝅘𝅥𝅯",
					name: "带斜线和符干的四分音符",
					ename: "Musical Symbol Quarter Note With Slashed Stem and Flag"
				},
				{char: "𝅘𝅥𝅰", name: "八分音符", ename: "Musical Symbol Eighth Note"},
				{char: "𝅘𝅥𝅱", name: "十六分音符", ename: "Musical Symbol Sixteenth Note"},
				{char: "𝅘𝅥𝅲", name: "三十二分音符", ename: "Musical Symbol Thirty-Second Note"},
				{char: "𝅥", name: "六十四分音符", ename: "Musical Symbol Sixty-Fourth Note"},
				{char: "𝅦", name: "一百二十八分音符", ename: "Musical Symbol One-Hundred-Twenty-Eighth Note"},
				{char: "𝅧", name: "二百五十六分音符", ename: "Musical Symbol Two-Hundred-Fifty-Sixth Note"},
				{char: "𝅨", name: "五百一十二分音符", ename: "Musical Symbol Five-Hundred-Twelfth Note"},
				{char: "𝅩", name: "一千零二十四分音符", ename: "Musical Symbol One-Thousand-Twenty-Fourth Note"},
				{char: "𝅪", name: "连音符", ename: "Musical Symbol Combining Augmentation Dot"},
				{char: "𝆒", name: "颤音记号", ename: "Musical Symbol Tremolo-1"},
				{char: "𝆓", name: "双颤音记号", ename: "Musical Symbol Tremolo-2"},
				{char: "𝆔", name: "三颤音记号", ename: "Musical Symbol Tremolo-3"},
				{char: "𝆕", name: "琶音上行", ename: "Musical Symbol Arpeggiato Up"},
				{char: "𝆖", name: "琶音下行", ename: "Musical Symbol Arpeggiato Down"},
				{char: "𝆗", name: "断音记号", ename: "Musical Symbol Staccato"},
				{char: "𝆘", name: "特断音记号", ename: "Musical Symbol Staccatissimo"},
				{char: "𝆙", name: "次断音记号", ename: "Musical Symbol Marcato"},
				{char: "𝆚", name: "下方次断音记号", ename: "Musical Symbol Marcato Below"},
				{char: "𝆛", name: "保持音记号", ename: "Musical Symbol Tenuto"},
				{char: "𝆜", name: "保持音断音记号", ename: "Musical Symbol Tenuto Staccato"},
				{char: "𝆝", name: "重音记号", ename: "Musical Symbol Accent"},
				{char: "𝆞", name: "下方重音记号", ename: "Musical Symbol Accent Below"},
				{char: "𝆟", name: "左指拨弦", ename: "Musical Symbol Left-Hand Pizzicato"},
				{char: "𝆠", name: "自然泛音", ename: "Musical Symbol Natural Harmonic"},
				{char: "𝆡", name: "人工泛音", ename: "Musical Symbol Artificial Harmonic"},
				{char: "𝆢", name: "上方 mordent", ename: "Musical Symbol Mordent"},
				{char: "𝆣", name: "下方 mordent", ename: "Musical Symbol Inverted Mordent"},
				{char: "𝆤", name: "回音", ename: "Musical Symbol Turn"},
				{char: "𝆥", name: "倒回音", ename: "Musical Symbol Inverted Turn"},
				{char: "𝆦", name: "颤音", ename: "Musical Symbol Trill"},
				{char: "𝆧", name: "上方颤音", ename: "Musical Symbol Upper Trill"},
				{char: "𝆨", name: "下方颤音", ename: "Musical Symbol Lower Trill"},
				{char: "𝆩", name: "上方普拉勒音", ename: "Musical Symbol Upper Pralltriller"},
				{char: "𝆪", name: "下方普拉勒音", ename: "Musical Symbol Lower Pralltriller"},
				{char: "𝆫", name: "上方普拉勒颤音", ename: "Musical Symbol Upper Pralltriller Trill"},
				{char: "𝆬", name: "下方普拉勒颤音", ename: "Musical Symbol Lower Pralltriller Trill"},
				{char: "𝆭", name: "上方 mordent 颤音", ename: "Musical Symbol Upper Mordent Trill"},
				{char: "𝆮", name: "下方 mordent 颤音", ename: "Musical Symbol Lower Mordent Trill"},
				{char: "𝆯", name: "上方回音颤音", ename: "Musical Symbol Upper Turn Trill"},
				{char: "𝆰", name: "下方回音颤音", ename: "Musical Symbol Lower Turn Trill"},
				{char: "𝆱", name: "上方颤音回音", ename: "Musical Symbol Upper Trill Turn"},
				{char: "𝆲", name: "下方颤音回音", ename: "Musical Symbol Lower Trill Turn"},
				{char: "𝆳", name: "上方普拉勒回音", ename: "Musical Symbol Upper Pralltriller Turn"},
				{char: "𝆴", name: "下方普拉勒回音", ename: "Musical Symbol Lower Pralltriller Turn"},
				{char: "𝆵", name: "上方 mordent 回音", ename: "Musical Symbol Upper Mordent Turn"},
				{char: "𝆶", name: "下方 mordent 回音", ename: "Musical Symbol Lower Mordent Turn"},
				{char: "𝆷", name: "上方回音普拉勒", ename: "Musical Symbol Upper Turn Pralltriller"},
				{char: "𝆸", name: "下方回音普拉勒", ename: "Musical Symbol Lower Turn Pralltriller"},
				{char: "𝆹", name: "上方颤音普拉勒", ename: "Musical Symbol Upper Trill Pralltriller"},
				{char: "𝆺", name: "下方颤音普拉勒", ename: "Musical Symbol Lower Trill Pralltriller"},
				{char: "𝆹𝅥", name: "上方普拉勒颤音普拉勒", ename: "Musical Symbol Upper Pralltriller Pralltriller"},
				{char: "𝆺𝅥", name: "下方普拉勒颤音普拉勒", ename: "Musical Symbol Lower Pralltriller Pralltriller"},
				{char: "𝆹𝅥𝅮", name: "连奏记号", ename: "Musical Symbol Slur"},
				{char: "𝆺𝅥𝅮", name: "连音线", ename: "Musical Symbol Tie"},
				{char: "𝆹𝅥𝅯", name: "连音线下方", ename: "Musical Symbol Tie Below"},
				{char: "𝆺𝅥𝅯", name: "连奏记号下方", ename: "Musical Symbol Slur Below"},
				{char: "𝇁", name: "乐句记号", ename: "Musical Symbol Phrase Mark"},
				{char: "𝇂", name: "乐句记号下方", ename: "Musical Symbol Phrase Mark Below"},
				{char: "𝇃", name: "渐强记号", ename: "Musical Symbol Crescendo"},
				{char: "𝇄", name: "渐弱记号", ename: "Musical Symbol Decrescendo"},
				{char: "𝇅", name: "渐强渐弱记号", ename: "Musical Symbol Crescendo Decrescendo"},
				{char: "𝇆", name: "渐弱渐强记号", ename: "Musical Symbol Decrescendo Crescendo"},
				{char: "𝇇", name: "极弱", ename: "Musical Symbol Pianissimo"},
				{char: "𝇈", name: "弱", ename: "Musical Symbol Piano"},
				{char: "𝇉", name: "中弱", ename: "Musical Symbol Mezzo Piano"},
				{char: "𝇊", name: "中强", ename: "Musical Symbol Mezzo Forte"},
				{char: "𝇋", name: "强", ename: "Musical Symbol Forte"},
				{char: "𝇌", name: "极强", ename: "Musical Symbol Fortissimo"},
				{char: "𝇍", name: "最弱", ename: "Musical Symbol Pianississimo"},
				{char: "𝇎", name: "最强", ename: "Musical Symbol Fortississimo"},
				{char: "𝇏", name: "突弱", ename: "Musical Symbol Sforzando"},
				{char: "𝇐", name: "突强", ename: "Musical Symbol Sforzato"},
				{char: "𝇑", name: "强后突弱", ename: "Musical Symbol Forte Piano"},
				{char: "𝇒", name: "强后即弱", ename: "Musical Symbol Forte-Piano"},
				{char: "𝇓", name: "渐强突弱", ename: "Musical Symbol Crescendo On One Note"},
				{char: "𝇔", name: "渐弱突强", ename: "Musical Symbol Decrescendo On One Note"},
				{char: "𝇕", name: "踏板记号", ename: "Musical Symbol Pedal Mark"},
				{char: "𝇖", name: "释放踏板记号", ename: "Musical Symbol Pedal Up Mark"},
				{char: "𝇗", name: "半踏板记号", ename: "Musical Symbol Half Pedal Mark"},
				{char: "𝇘", name: "持续音踏板记号", ename: "Musical Symbol Sustenuto Pedal Mark"},
				{char: "𝇙", name: "柔音踏板记号", ename: "Musical Symbol Una Corda"},
				{char: "𝇚", name: "三弦踏板记号", ename: "Musical Symbol Tre Corde"},
				{char: "𝇛", name: "制音器上提", ename: "Musical Symbol With Dampers"},
				{char: "𝇜", name: "制音器放下", ename: "Musical Symbol Without Dampers"},
				{char: "𝇝", name: "二连音", ename: "Musical Symbol Duplet"},
				{char: "𝇞", name: "三连音", ename: "Musical Symbol Triplet"},
				{char: "𝇟", name: "四连音", ename: "Musical Symbol Quadruplet"},
				{char: "𝇠", name: "五连音", ename: "Musical Symbol Quintuplet"},
				{char: "𝇡", name: "六连音", ename: "Musical Symbol Sextuplet"},
				{char: "𝇢", name: "七连音", ename: "Musical Symbol Septuplet"},
				{char: "𝇣", name: "八连音", ename: "Musical Symbol Octuplet"},
				{char: "𝇤", name: "九连音", ename: "Musical Symbol Nonuplet"},
				{char: "𝇥", name: "十连音", ename: "Musical Symbol Decuplet"},
				{char: "𝇦", name: "十一连音", ename: "Musical Symbol Undecuplet"},
				{char: "𝇧", name: "十二连音", ename: "Musical Symbol Duodecuplet"},
				{char: "𝇨", name: "十三连音", ename: "Musical Symbol Tredecuplet"},
				{char: "𝇩", name: "十四连音", ename: "Musical Symbol Quattuordecuplet"},
				{char: "𝇪", name: "十五连音", ename: "Musical Symbol Quindecuplet"},
				{char: "♩", name: "四分音符", ename: "Quarter Note", tags: ['音乐', '音符']},
				{char: "♪", name: "八分音符", ename: "Eighth Note", tags: ['音乐', '音符']},
				{char: "♫", name: "连八分音符", ename: "Beamed Eighth Notes", tags: ['音乐', '音符']},
				{char: "♬", name: "连十六分音符", ename: "Beamed Sixteenth Notes", tags: ['音乐', '音符']},
				{char: "♭", name: "降号", ename: "Music Flat Sign", tags: ['音乐', '降号']},
				{char: "♮", name: "还原号", ename: "Music Natural Sign", tags: ['音乐', '还原号']},
				{char: "♯", name: "升号", ename: "Music Sharp Sign", tags: ['音乐', '升号']}
			]
		},
		{
			name: "箭头、方向",
			symbols: [
				{char: "↑", name: "上箭头", ename: "Upwards Arrow"},
				{char: "↓", name: "下箭头", ename: "Downwards Arrow"},
				{char: "←", name: "左箭头", ename: "Leftwards Arrow"},
				{char: "→", name: "右箭头", ename: "Rightwards Arrow"},
				{char: "↖", name: "左上箭头", ename: "North West Arrow"},
				{char: "↗", name: "右上箭头", ename: "North East Arrow"},
				{char: "↘", name: "右下箭头", ename: "South East Arrow"},
				{char: "↙", name: "左下箭头", ename: "South West Arrow"},
				{char: "↔", name: "左右箭头", ename: "Left Right Arrow"},
				{char: "↕", name: "上下箭头", ename: "Up Down Arrow"},
				{char: "⇦", name: "左双箭头", ename: "Leftwards Paired Arrows"},
				{char: "⇧", name: "上双箭头", ename: "Upwards Paired Arrows"},
				{char: "⇨", name: "右双箭头", ename: "Rightwards Paired Arrows"},
				{char: "⇩", name: "下双箭头", ename: "Downwards Paired Arrows"},
				{char: "⇪", name: "caps lock", ename: "Upwards Arrow From Bar"},
				{char: "➔", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➘", name: "右下粗箭头", ename: "Heavy South East Arrow"},
				{char: "➙", name: "右上粗箭头", ename: "Heavy North East Arrow"},
				{char: "➚", name: "右上粗箭头", ename: "Heavy North East Arrow"},
				{char: "➛", name: "右箭头", ename: "Rightwards Arrow"},
				{char: "➜", name: "粗圆头右箭头", ename: "Heavy Round-Tipped Rightwards Arrow"},
				{char: "➝", name: "三角头右箭头", ename: "Triangle-Headed Rightwards Arrow"},
				{char: "➞", name: "粗三角头右箭头", ename: "Heavy Triangle-Headed Rightwards Arrow"},
				{char: "➟", name: "虚线三角头右箭头", ename: "Dashed Triangle-Headed Rightwards Arrow"},
				{char: "➠", name: "粗虚线三角头右箭头", ename: "Heavy Dashed Triangle-Headed Rightwards Arrow"},
				{char: "➡", name: "黑三角右箭头", ename: "Black Rightwards Arrow"},
				{char: "➢", name: "三维顶灯右箭头", ename: "Three-D Top-Lighted Rightwards Arrowhead"},
				{char: "➣", name: "三维底灯右箭头", ename: "Three-D Bottom-Lighted Rightwards Arrowhead"},
				{char: "➤", name: "黑三角", ename: "Black Rightwards Arrowhead"},
				{char: "➥", name: "旋转粗右箭头", ename: "Heavy Rightwards Arrow With Tip Downwards"},
				{char: "➦", name: "圆圈内右箭头", ename: "Rightwards Arrow With Tip Towards Top-Left Corner"},
				{char: "➧", name: "重黑三角", ename: "Heavy Black Curved Upwards and Rightwards Arrow"},
				{char: "➨", name: "曲线右箭头", ename: "Right-Side Arc-Ended Arrow"},
				{char: "➩", name: "曲线粗右箭头", ename: "Heavy Right-Side Arc-Ended Arrow"},
				{char: "➪", name: "曲线三角头右箭头", ename: "Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➫", name: "曲线粗三角头右箭头", ename: "Heavy Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➬", name: "曲线虚线三角头右箭头", ename: "Dashed Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➭", name: "曲线粗虚线三角头右箭头", ename: "Heavy Dashed Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➮", name: "波浪线右箭头", ename: "Wave-Lined Rightwards Arrow"},
				{char: "➯", name: "带垂直笔划的波浪线右箭头", ename: "Wave-Lined Rightwards Arrow With Vertical Stroke"},
				{char: "➱", name: "右上双箭头", ename: "Rightwards Two-Headed Arrow With Vertical Stroke"},
				{char: "➲", name: "粗右上双箭头", ename: "Heavy Rightwards Two-Headed Arrow With Vertical Stroke"},
				{char: "➳", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➴", name: "右下箭头", ename: "Heavy South East Arrow"},
				{char: "➵", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➶", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➷", name: "左下箭头", ename: "Heavy South West Arrow"},
				{char: "➸", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➹", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➺", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➻", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➼", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➽", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➾", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "☚", name: "黑左指", ename: "Black Left Pointing Index", tags: ['手指', '指向']},
				{char: "☛", name: "黑右指", ename: "Black Right Pointing Index", tags: ['手指', '指向']},
				{char: "☜", name: "白左指", ename: "White Left Pointing Index", tags: ['手指', '指向']},
				{char: "☝", name: "白上指", ename: "White Up Pointing Index", tags: ['手指', '指向']},
				{char: "☞", name: "白右指", ename: "White Right Pointing Index", tags: ['手指', '指向']},
				{char: "☟", name: "白下指", ename: "White Down Pointing Index", tags: ['手指', '指向']},

				{char: "⚞", name: "右聚三线", ename: "Three Lines Converging Right", tags: ['汇聚']},
				{char: "⚟", name: "左聚三线", ename: "Three Lines Converging Left", tags: ['汇聚']},
			]
		}
	]
};