const data = {
	name: '人类活动',
	groups: [
		{
			name: '表情',
			symbols: [
				{char: "☺", name: "白笑脸", ename: "WHITE SMILING FACE", tags: ['高兴', '开心']},
				{char: "☻", name: "黑笑脸", ename: "BLACK SMILING FACE", tags: ['高兴', '开心']},
				{char: "☹", name: "白皱眉", ename: "WHITE FROWNING FACE", tags: []}
			]
		},
		{
			name: '日常用品和概念',
			symbols: [
				{char: "♂", name: "男性、雄性", ename: "Male", tags: []},
				{char: "♀", name: "女性、雌性", ename: "Female", tags: []},
				{char: "⚢", name: "双女", ename: "Doubled Female Sign", tags: ['女性', '双胞胎', '女同性恋']},
				{char: "⚣", name: "双男", ename: "Doubled Male Sign", tags: ['男性', '双胞胎', '男同性恋']},
				{char: "⚤", name: "男女", ename: "Interlaced Male and Female Sign", tags: ['性别', '结合', '双性恋', '异性恋']},
				{char: "⚥", name: "双性", ename: "Male and Female Sign", tags: ['性别', '中性']},
				{char: "⚦", name: "男", ename: "Male with Stroke Sign", tags: ['性别', '男性']},
				{char: "⚧", name: "跨性别", ename: "Male with Stroke and Male and Female Sign", tags: ['性别', '男性']},
				{char: "⚨", name: "垂直男", ename: "Vertical Male with Stroke Sign", tags: ['性别', '男性']},
				{char: "⚩", name: "水平男", ename: "Horizontal Male with Stroke Sign", tags: ['性别', '男性']},
				{char: "⚲", name: "中性、无性别", ename: "Neuter", tags: ['性别', '中性']},
				{char: "⚭", name: "婚姻", ename: "Marriage Symbol", tags: ['婚姻', '结合']},
				{char: "⚮", name: "离婚", ename: "Divorce Symbol", tags: ['离婚', '分离']},
				{char: "⚯", name: "未婚", ename: "Unmarried Partnership Symbol", tags: ['未婚', '关系']},
				{char: "⚰", name: "棺材", ename: "Coffin", tags: ['死亡', '葬礼']},
				{char: "⚱", name: "骨灰盒", ename: "Funeral Urn", tags: ['死亡', '葬礼']},
				{char: "☎", name: "黑电话", ename: "Black Telephone"},
				{char: "☏", name: "白电话", ename: "White Telephone"},
				{char: "☐", name: "投票框", ename: "Ballot Box"},
				{char: "☑", name: "带勾的投票框", ename: "Ballot Box with Check"},
				{char: "☒", name: "带叉的投票框", ename: "Ballot Box with X"},
				{char: "⛲", name: "喷泉", ename: "Fountain", tags: ['喷泉', '水']},
				{char: "☠", name: "骷髅和交叉骨", ename: "Skull and Crossbones", tags: ['海盗']},
				{char: "☡", name: "警告标志", ename: "Caution Sign"},
				{char: "☢", name: "放射性标志", ename: "Radioactive Sign", tags: ['辐射']},
				{char: "☣", name: "生物危害标志", ename: "Biohazard Sign", tags: ['生化']},
				{char: "♲", name: "回收符号", ename: "Universal Recycling Symbol", tags: ['环保', '回收']},
				{char: "♳", name: "回收符号", ename: "Recycling Symbol for Type-1 Plastics", tags: ['环保', '回收', '塑料']},
				{char: "♴", name: "回收符号", ename: "Recycling Symbol for Type-2 Plastics", tags: ['环保', '回收', '塑料']},
				{char: "♵", name: "回收符号", ename: "Recycling Symbol for Type-3 Plastics", tags: ['环保', '回收', '塑料']},
				{char: "♶", name: "回收符号", ename: "Recycling Symbol for Type-4 Plastics", tags: ['环保', '回收', '塑料']},
				{char: "♷", name: "回收符号", ename: "Recycling Symbol for Type-5 Plastics", tags: ['环保', '回收', '塑料']},
				{char: "♸", name: "回收符号", ename: "Recycling Symbol for Type-6 Plastics", tags: ['环保', '回收', '塑料']},
				{char: "♹", name: "回收符号", ename: "Recycling Symbol for Type-7 Plastics", tags: ['环保', '回收', '塑料']},
				{char: "♺", name: "回收符号", ename: "Recycling Symbol for Generic Materials", tags: ['环保', '回收']},
				{char: "♻", name: "回收符号", ename: "Black Universal Recycling Symbol", tags: ['环保', '回收']},
				{char: "♼", name: "回收符号", ename: "Recycled Paper Symbol", tags: ['环保', '回收', '纸张']},
				{char: "♽", name: "回收符号", ename: "Partially-Recycled Paper Symbol", tags: ['环保', '回收', '纸张']},
				{char: "♾", name: "回收符号", ename: "Permanent Paper Sign", tags: ['环保', '回收', '纸张']},
				{char: "♿", name: "轮椅", ename: "Wheelchair Symbol", tags: ['无障碍', '轮椅']},
				{char: "🚬", name: "吸烟", ename: "Smoking", tags: ['吸烟', '健康']},
				{char: "🚭", name: "禁止吸烟", ename: "No Smoking", tags: ['禁止吸烟', '健康']},
				{char: "🚮", name: "请勿乱扔垃圾", ename: "Put Litter in Its Place", tags: ['环保', '垃圾']},
				{char: "🚯", name: "请勿乱扔垃圾", ename: "No Littering", tags: ['环保', '垃圾']},
				{char: "🚰", name: "饮用水", ename: "Potable Water", tags: ['饮用水', '健康']},
				{char: "🚱", name: "非饮用水", ename: "Non-Potable Water", tags: ['非饮用水', '健康']},
				{char: "🚫", name: "禁止", ename: "Prohibited", tags: ['禁止', '交通']},
				{char: "🚹", name: "男士洗手间", ename: "Men's Room", tags: ['男士洗手间', '洗手间']},
				{char: "🚺", name: "女士洗手间", ename: "Women's Room", tags: ['女士洗手间', '洗手间']},
				{char: "🚻", name: "洗手间", ename: "Restroom", tags: ['洗手间', '设施']},
				{char: "🚼", name: "婴儿换尿布台", ename: "Baby Symbol", tags: ['婴儿换尿布台', '设施']},
				{char: "🚽", name: "马桶", ename: "Toilet", tags: ['设施']},
				{char: "🚾", name: "厕所/洗手间", ename: "Water Closet", tags: ['设施']},
				{char: "🚿", name: "淋浴", ename: "Shower", tags: ['设施']},
				{char: "🛀", name: "浴缸", ename: "Bath", tags: ['设施']},
				{char: "🛁", name: "浴缸", ename: "Bathtub", tags: ['设施']},
				{char: "⚐", name: "白旗", ename: "WHITE FLAG", tags: []},
				{char: "⚑", name: "黑旗", ename: "BLACK FLAG", tags: []},
				{char: "⚒", name: "锤子和镐", ename: "HAMMER AND PICK", tags: []},
				{
					char: "⚕", name: "阿斯克勒庇俄斯之杖", ename: "Staff of Aesculapius",
					tags: ['古希腊', '医生', "医疗", "健康", '蛇杖', '医神杖']
				},
				{char: "⚖", name: "天平", ename: "Scales", tags: ["法律", "公正", "平衡", "审判"]},
				{char: "⚙", name: "齿轮", ename: "Gear", tags: ["机械", "工具", "工程", "设置"]},
				{char: "⚿", name: "带框钥匙", ename: " SQUARED KEY", tags: []},
				{char: "🚩", name: "三角旗", ename: "Triangular Flag", tags: ['三角旗', '旗帜']},
				{char: "⛏", name: "十字镐、矿镐", ename: "PICK", tags: []},
				{char: "⛓", name: "链条", ename: "CHAINS", tags: []},
				{
					char: "⛞", name: "黑方块中白圈内的斜线", ename: "FALLING DIAGONAL IN WHITE CIRCLE IN BLACK SQUARE",
					tags: ["符号", "警告"]
				},
				{char: "⛭", name: "无毂齿轮", ename: "GEAR WITHOUT HUB", tags: ["工具", "机械"]},
				{char: "⛮", name: "带手柄的齿轮", ename: "GEAR WITH HANDLES", tags: ["工具", "机械"]},
				{char: "⛼", name: "墓碑", ename: "HEADSTONE GRAVEYARD SYMBOL", tags: ["宗教", "墓地"]},
				{
					char: "⛿",
					name: "带水平黑条的白色旗",
					ename: "WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE",
					tags: ["旗帜", "符号"]
				}
			]
		},
		{
			name: "经济、商业、货币",
			symbols: [
				{char: "⚚", name: "墨丘利之杖", ename: "Staff of Hermes", tags: ['古希腊', "神话", '商神杖', "商业", "沟通"]},
				{char: "☤", name: "卡杜/商神杖", ename: "Caduceus", tags: ['古希腊', "神话", '墨丘利之杖']},
				{char: "⚖", name: "天平", ename: "Scales", tags: ["法律", "公正", "平衡", "审判"]},
				{
					char: "$", name: "美元", ename: "Dollar",
					tags: ["货币", "钱", '美国', '加拿大', '澳大利亚', '新加坡', '新西兰', '香港']
				},
				{char: "¢", name: "分", ename: "Cent", tags: ["货币", "钱"]},
				{char: "£", name: "英镑", ename: "Pound", tags: ["货币", "钱", '英国']},
				{char: "¤", name: "货币", ename: "Currency", tags: ["货币", "钱"]},
				{char: "¥", name: "人民币、日元", ename: "Yuan, Yen", tags: ["货币", "钱", '中国', '日本', '元', '円']},
				{char: "֏", name: "亚美尼亚德拉姆", ename: "Armenian Dram", tags: ["货币", "钱"]},
				{char: "؋", name: "阿富汗尼", ename: "Afghani", tags: ["货币", "钱"]},
				{char: "₲", name: "巴拉圭瓜拉尼", ename: "Guarani", tags: ["货币", "钱"]},
				{char: "₵", name: "加纳塞地", ename: "Cedi", tags: ["货币", "钱"]},
				{char: "₸", name: "哈萨克斯坦坚戈", ename: "Tenge", tags: ["货币", "钱"]},
				{char: "₺", name: "土耳其里拉", ename: "Turkish Lira", tags: ["货币", "钱"]},
				{char: "₼", name: "阿塞拜疆马纳特", ename: "Manat", tags: ["货币", "钱"]},
				{char: "₾", name: "格鲁吉亚拉里", ename: "Lari", tags: ["货币", "钱"]},
				{char: "₿", name: "比特币", ename: "Bitcoin", tags: ["货币", "钱"]},
				{char: "€", name: "欧元", ename: "Euro", tags: ["货币", "钱"]},
				{char: "₨", name: "卢比", ename: "Rupee", tags: ["货币", "钱"]},
				{char: "₩", name: "朝鲜元、韩元", ename: "Won", tags: ["货币", "钱"]},
				{char: "₪", name: "以色列新谢克尔", ename: "New Shekel", tags: ["货币", "钱"]},
				{char: "₫", name: "越南盾", ename: "Dong", tags: ["货币", "钱"]},
				{char: "₭", name: "老挝基普", ename: "Kip", tags: ["货币", "钱"]},
				{char: "₮", name: "蒙古图格里克", ename: "Tugrik", tags: ["货币", "钱"]},
				{char: "₥", name: "密尔", ename: "Mill", tags: ["货币", "钱"]},
				{char: "₦", name: "尼日利亚奈拉", ename: "Naira", tags: ["货币", "钱"]},
				{char: "₧", name: "西班牙比塞塔", ename: "Peseta", tags: ["货币", "钱"]},
				{char: "₴", name: "乌克兰格里夫纳", ename: "Hryvnia", tags: ["货币", "钱"]},
				{char: "₹", name: "印度卢比", ename: "Indian Rupee", tags: ["货币", "钱"]},
				{char: "₽", name: "俄罗斯卢布", ename: "Ruble", tags: ["货币", "钱"]},
				{char: "⛻", name: "日本银行", ename: "Japanese Bank Symbol", tags: []}
			]
		},
		{
			name: '建筑',
			symbols: [
				{char: "⛨", name: "黑教堂、盾牌黑十字", ename: "Black Cross On Shield", tags: []},
				{char: "⛩", name: "神社鸟居/神道教神社", ename: "Shinto Shrine", tags: ['日本']},
				{char: "⛪", name: "教堂", ename: "Church", tags: []},
				{char: "⛫", name: "城堡", ename: "Castle", tags: ['城堡', '建筑']},
				{char: "⛬", name: "历史遗址", ename: "Historic Site", tags: ['遗址', '历史']},
				{char: "⛯", name: "灯塔", ename: "MAP SYMBOL FOR LIGHTHOUSE", tags: ["地图", "航海"]}
			]
		},
		{
			name: '饮食',
			symbols: [
				{char: "⛾", name: "黑方块上的杯子", ename: "CUP ON BLACK SQUARE", tags: ["物品", "符号"]},
				{char: "☕", name: "热饮", ename: "Hot Beverage", tags: ["咖啡"]}
			]
		},
		{
			name: '出行、交通、旅游',
			symbols: [
				{char: "☂", name: "雨伞", ename: "Umbrella"},
				{char: "☔", name: "带雨滴的雨伞", ename: "Umbrella with Rain Drops"},
				{char: "⛱", name: "地面雨伞", ename: "Umbrella On Ground", tags: ['雨伞', '地面']},
				{char: "⛟", name: "黑色卡车", ename: "BLACK TRUCK", tags: ["交通", "车辆"]},
				{char: "⛴", name: "渡轮", ename: "FERRY", tags: ["交通", "航海"]},
				{char: "⛺", name: "帐篷", ename: "Tent", tags: ['帐篷', '露营']},
				{char: "⛵", name: "帆船", ename: "Sailboat", tags: []},
				{char: "🚀", name: "火箭", ename: "Rocket", tags: ['火箭', '太空', '发射']},
				{char: "🚁", name: "直升机", ename: "Helicopter", tags: ['直升机', '飞行器']},
				{char: "🚂", name: "蒸汽机车", ename: "Steam Locomotive", tags: ['火车', '蒸汽']},
				{char: "🚃", name: "电车", ename: "Railway Car", tags: ['电车', '铁路']},
				{char: "🚄", name: "高速列车", ename: "High-Speed Train", tags: ['火车', '高速']},
				{char: "🚅", name: "子弹头列车", ename: "Bullet Train", tags: ['火车', '子弹头']},
				{char: "🚆", name: "火车", ename: "Train", tags: ['火车', '铁路']},
				{char: "🚇", name: "地铁", ename: "Metro", tags: ['地铁', '地下']},
				{char: "🚈", name: "轻轨", ename: "Light Rail", tags: ['轻轨', '铁路']},
				{char: "🚉", name: "车站", ename: "Station", tags: ['车站', '交通']},
				{char: "🚊", name: "电车", ename: "Tram", tags: ['电车', '城市交通']},
				{char: "🚋", name: "电车", ename: "Tram Car", tags: ['电车', '城市交通']},
				{char: "🚌", name: "公共汽车", ename: "Bus", tags: ['公共汽车', '城市交通']},
				{char: "🚍", name: "迎面而来的公共汽车", ename: "Oncoming Bus", tags: ['公共汽车', '城市交通']},
				{char: "🚎", name: "无轨电车", ename: "Trolleybus", tags: ['无轨电车', '城市交通']},
				{char: "🚏", name: "公共汽车站", ename: "Bus Stop", tags: ['公共汽车站', '交通']},
				{char: "🚐", name: "小巴", ename: "Minibus", tags: ['小巴', '城市交通']},
				{char: "🚑", name: "救护车", ename: "Ambulance", tags: ['救护车', '医疗']},
				{char: "🚒", name: "消防车", ename: "Fire Engine", tags: ['消防车', '消防']},
				{char: "🚓", name: "警车", ename: "Police Car", tags: ['警车', '警察']},
				{char: "🚔", name: "迎面而来的警车", ename: "Oncoming Police Car", tags: ['警车', '警察']},
				{char: "🚕", name: "出租车", ename: "Taxi", tags: ['出租车', '城市交通']},
				{char: "🚖", name: "迎面而来的出租车", ename: "Oncoming Taxi", tags: ['出租车', '城市交通']},
				{char: "🚗", name: "汽车", ename: "Automobile", tags: ['汽车', '交通工具']},
				{char: "🚘", name: "迎面而来的汽车", ename: "Oncoming Automobile", tags: ['汽车', '交通工具']},
				{char: "🚙", name: "运动型多用途车", ename: "Sport Utility Vehicle", tags: ['SUV', '汽车']},
				{char: "🚚", name: "货车", ename: "Delivery Truck", tags: ['货车', '运输']},
				{char: "🚛", name: "铰接式货车", ename: "Articulated Lorry", tags: ['货车', '运输']},
				{char: "🚜", name: "拖拉机", ename: "Tractor", tags: ['拖拉机', '农业']},
				{char: "🚝", name: "单轨铁路", ename: "Monorail", tags: ['单轨铁路', '铁路']},
				{char: "🚞", name: "山区铁路", ename: "Mountain Railway", tags: ['山区铁路', '铁路']},
				{char: "🚟", name: "悬索铁路", ename: "Suspension Railway", tags: ['悬索铁路', '铁路']},
				{char: "🚠", name: "山地缆车", ename: "Mountain Cableway", tags: ['山地缆车', '缆车']},
				{char: "🚡", name: "空中缆车", ename: "Aerial Tramway", tags: ['空中缆车', '缆车']},
				{char: "🚢", name: "轮船", ename: "Ship", tags: ['轮船', '海运']},
				{char: "🚣", name: "划船的人", ename: "Person Rowing Boat", tags: ['划船', '水上运动']},
				{char: "🚤", name: "快艇", ename: "Speedboat", tags: ['快艇', '水上运动']},
				{char: "🚥", name: "水平交通信号灯", ename: "Horizontal Traffic Light", tags: ['交通信号灯', '交通']},
				{char: "🚦", name: "垂直交通信号灯", ename: "Vertical Traffic Light", tags: ['交通信号灯', '交通']},
				{char: "🚧", name: "施工", ename: "Construction", tags: ['施工', '道路']},
				{char: "🚨", name: "旋转的警灯", ename: "Rotating Light", tags: ['警灯', '警察']},
				{char: "🚪", name: "门", ename: "Door", tags: ['门', '建筑']},
				{char: "🚫", name: "禁止", ename: "Prohibited", tags: ['禁止', '交通']},
				{char: "🚲", name: "自行车", ename: "Bicycle", tags: ['自行车', '交通工具']},
				{char: "🚳", name: "禁止自行车", ename: "No Bicycles", tags: ['禁止自行车', '交通']},
				{char: "🚴", name: "骑自行车的人", ename: "Person Biking", tags: ['骑自行车', '运动']},
				{char: "🚵", name: "骑山地自行车的人", ename: "Person Mountain Biking", tags: ['骑山地自行车', '运动']},
				{char: "🚶", name: "行人", ename: "Person Walking", tags: ['行人', '交通']},
				{char: "🚷", name: "禁止行人", ename: "No Pedestrians", tags: ['禁止行人', '交通']},
				{char: "🚸", name: "儿童过马路", ename: "Children Crossing", tags: ['儿童过马路', '交通']},
				{char: "🛂", name: "护照检查", ename: "Passport Control", tags: ['护照检查', '海关']},
				{char: "🛃", name: "海关", ename: "Customs", tags: ['海关', '边境']},
				{char: "🛄", name: "行李提取", ename: "Baggage Claim", tags: ['行李提取', '机场']},
				{char: "🛅", name: "行李寄存", ename: "Left Luggage", tags: ['行李寄存', '机场']},
				{char: "⛽", name: "燃油泵", ename: "FUEL PUMP", tags: ["交通", "汽车"]},
				{char: "♨", name: "温泉", ename: "HOT SPRING", tags: []},
				{char: "⚓", name: "船锚", ename: "ANCHOR", tags: []},
				{char: "⛌", name: "交通标志·交叉车道", ename: "CROSSING LANES", tags: []},
				{char: "⛍", name: "交通标志·故障车辆", ename: "DISABLED CAR", tags: []},
				{char: "⛐", name: "交通标志·车辆侧滑", ename: "CAR SLIDING", tags: []},
				{char: "⛑", name: "带白十字的头盔（救援/安全）", ename: "HELMET WITH WHITE CROSS", tags: []},
				{char: "⛒", name: "圆圈内的交叉车道", ename: "CIRCLED CROSSING LANES", tags: []},
				{char: "⛔", name: "禁止进入", ename: "NO ENTRY", tags: []},
				{char: "⛕", name: "交替单向左行交通", ename: "ALTERNATE ONE-WAY LEFT WAY TRAFFIC", tags: []},
				{char: "⛖", name: "黑色双向左行交通", ename: "BLACK TWO-WAY LEFT WAY TRAFFIC", tags: []},
				{char: "⛗", name: "白色双向左行交通", ename: "WHITE TWO-WAY LEFT WAY TRAFFIC", tags: ["交通", "道路"]},
				{char: "⛘", name: "黑色左车道合并", ename: "BLACK LEFT LANE MERGE", tags: ["交通", "道路"]},
				{char: "⛙", name: "白色左车道合并", ename: "WHITE LEFT LANE MERGE", tags: ["交通", "道路"]},
				{char: "⛚", name: "慢行标志", ename: "DRIVE SLOW SIGN", tags: ["交通", "警告"]},
				{char: "⛜", name: "左侧入口关闭", ename: "LEFT CLOSED ENTRY", tags: ["交通", "道路"]},
				{char: "⛠", name: "限制左转入口-1", ename: "RESTRICTED LEFT ENTRY-1", tags: ["交通", "道路"]},
				{char: "⛡", name: "限制左转入口-2", ename: "RESTRICTED LEFT ENTRY-2", tags: ["交通", "道路"]}
			]
		},
		{
			name: '艺术',
			symbols: []
		},
		{
			name: '音乐',
			symbols: [
				{char: "𝅝", name: "全音符", ename: "Whole Note"},
				{char: "𝅗𝅥", name: "二分音符", ename: "Half Note"},
				{char: "♩", name: "四分音符", ename: "Quarter Note"},
				{char: "♪", name: "八分音符", ename: "Eighth Note"},
				{char: "♫", name: "双八分音符", ename: "Beamed Eighth Notes"},
				{char: "♬", name: "十六分音符", ename: "Beamed Sixteenth Notes"},
				{char: "♭", name: "降号", ename: "Music Flat Sign"},
				{char: "♮", name: "本位号", ename: "Music Natural Sign"},
				{char: "♯", name: "升号", ename: "Music Sharp Sign"},
				{char: "𝄀", name: "单竖线", ename: "Musical Symbol Single Barline"},
				{char: "𝄁", name: "双竖线", ename: "Musical Symbol Double Barline"},
				{char: "𝄂", name: "终止线", ename: "Musical Symbol Final Barline"},
				{char: "𝄃", name: "反向终止线", ename: "Musical Symbol Reverse Final Barline"},
				{char: "𝄄", name: "虚线小节线", ename: "Musical Symbol Dashed Barline"},
				{char: "𝄅", name: "短小节线", ename: "Musical Symbol Short Barline"},
				{char: "𝄆", name: "左重复线", ename: "Musical Symbol Left Repeat Sign"},
				{char: "𝄇", name: "右重复线", ename: "Musical Symbol Right Repeat Sign"},
				{char: "𝄈", name: "重复点", ename: "Musical Symbol Repeat Dots"},
				{char: "𝄉", name: "从记号处反复", ename: "Musical Symbol Dal Segno"},
				{char: "𝄊", name: "从头反复", ename: "Musical Symbol Da Capo"},
				{char: "𝄋", name: "记号", ename: "Musical Symbol Segno"},
				{char: "𝄌", name: "尾声", ename: "Musical Symbol Coda"},
				{char: "𝄍", name: "重复图样1", ename: "Musical Symbol Repeated Figure-1"},
				{char: "𝄎", name: "重复图样2", ename: "Musical Symbol Repeated Figure-2"},
				{char: "𝄏", name: "重复图样3", ename: "Musical Symbol Repeated Figure-3"},
				{char: "𝄐", name: "延长记号", ename: "Musical Symbol Fermata"},
				{char: "𝄑", name: "下方延长记号", ename: "Musical Symbol Fermata Below"},
				{char: "𝄒", name: "呼吸记号", ename: "Musical Symbol Breath Mark"},
				{char: "𝄓", name: "休止记号", ename: "Musical Symbol Caesura"},
				{char: "𝄔", name: "花括号", ename: "Musical Symbol Brace"},
				{char: "𝄕", name: "方括号", ename: "Musical Symbol Bracket"},
				{char: "𝄖", name: "单线谱", ename: "Musical Symbol One-Line Staff"},
				{char: "𝄗", name: "双线谱", ename: "Musical Symbol Two-Line Staff"},
				{char: "𝄘", name: "三线谱", ename: "Musical Symbol Three-Line Staff"},
				{char: "𝄙", name: "四线谱", ename: "Musical Symbol Four-Line Staff"},
				{char: "𝄚", name: "五线谱", ename: "Musical Symbol Five-Line Staff"},
				{char: "𝄛", name: "六线谱", ename: "Musical Symbol Six-Line Staff"},
				{char: "𝄜", name: "六弦指板", ename: "Musical Symbol Six-String Fretboard"},
				{char: "𝄝", name: "四弦指板", ename: "Musical Symbol Four-String Fretboard"},
				{char: "𝄞", name: "G谱号", ename: "Musical Symbol G Clef"},
				{char: "𝄟", name: "G谱号高八度", ename: "Musical Symbol G Clef Ottava Alta"},
				{char: "𝄠", name: "G谱号低八度", ename: "Musical Symbol G Clef Ottava Bassa"},
				{char: "𝄡", name: "C谱号", ename: "Musical Symbol C Clef"},
				{char: "𝄢", name: "F谱号", ename: "Musical Symbol F Clef"},
				{char: "𝄣", name: "F谱号高八度", ename: "Musical Symbol F Clef Ottava Alta"},
				{char: "𝄤", name: "F谱号低八度", ename: "Musical Symbol F Clef Ottava Bassa"},
				{char: "𝄥", name: "打击乐谱号1", ename: "Musical Symbol Drum Clef-1"},
				{char: "𝄦", name: "打击乐谱号2", ename: "Musical Symbol Drum Clef-2"},
				{char: "𝄩", name: "多小节休止符", ename: "Musical Symbol Multiple Measure Rest"},
				{char: "𝄪", name: "重升号", ename: "Musical Symbol Double Sharp"},
				{char: "𝄫", name: "重降号", ename: "Musical Symbol Double Flat"},
				{char: "𝄬", name: "降半音号", ename: "Musical Symbol Flat Up"},
				{char: "𝄭", name: "升半音号", ename: "Musical Symbol Flat Down"},
				{char: "𝄮", name: "四分之一音升号", ename: "Musical Symbol Quarter Tone Sharp"},
				{char: "𝄯", name: "四分之一音降号", ename: "Musical Symbol Quarter Tone Flat"},
				{char: "𝅅", name: "长休止符", ename: "Musical Symbol Longa Rest"},
				{char: "𝅆", name: "双全休止符", ename: "Musical Symbol Breve Rest"},
				{char: "𝅇", name: "全休止符", ename: "Musical Symbol Whole Rest"},
				{char: "𝅈", name: "二分休止符", ename: "Musical Symbol Half Rest"},
				{char: "𝅉", name: "四分休止符", ename: "Musical Symbol Quarter Rest"},
				{char: "𝅊", name: "八分休止符", ename: "Musical Symbol Eighth Rest"},
				{char: "𝅋", name: "十六分休止符", ename: "Musical Symbol Sixteenth Rest"},
				{char: "𝅌", name: "三十二分休止符", ename: "Musical Symbol Thirty-Second Rest"},
				{char: "𝅍", name: "六十四分休止符", ename: "Musical Symbol Sixty-Fourth Rest"},
				{char: "𝅎", name: "一百二十八分休止符", ename: "Musical Symbol One-Hundred-Twenty-Eighth Rest"},
				{char: "𝅏", name: "二百五十六分休止符", ename: "Musical Symbol Two-Hundred-Fifty-Sixth Rest"},
				{char: "𝅐", name: "五百一十二分休止符", ename: "Musical Symbol Five-Hundred-Twelfth Rest"},
				{char: "𝅑", name: "一千零二十四分休止符", ename: "Musical Symbol One-Thousand-Twenty-Fourth Rest"},
				{char: "𝅒", name: "长音符", ename: "Musical Symbol Longa Note"},
				{char: "𝅓", name: "双全音符", ename: "Musical Symbol Breve Note"},
				{char: "𝅔", name: "有符干的双全音符", ename: "Musical Symbol Breve Note With Stem"},
				{char: "𝅕", name: "带斜线的双全音符", ename: "Musical Symbol Breve Note With Slashed Stem"},
				{
					char: "𝅖",
					name: "带斜线和符干的双全音符",
					ename: "Musical Symbol Breve Note With Slashed Stem and Flag"
				},
				{char: "𝅗", name: "黑双全音符", ename: "Musical Symbol Black Breve Note"},
				{char: "𝅘", name: "带符干的黑双全音符", ename: "Musical Symbol Black Breve Note With Stem"},
				{
					char: "𝅙",
					name: "带斜线和符干的黑双全音符",
					ename: "Musical Symbol Black Breve Note With Slashed Stem and Flag"
				},
				{char: "𝅚", name: "全音符", ename: "Musical Symbol Whole Note"},
				{char: "𝅛", name: "带符干的全音符", ename: "Musical Symbol Whole Note With Stem"},
				{char: "𝅜", name: "带斜线和符干的全音符", ename: "Musical Symbol Whole Note With Slashed Stem and Flag"},
				{char: "𝅝", name: "空心二分音符", ename: "Musical Symbol Void Half Note"},
				{char: "𝅗𝅥", name: "二分音符", ename: "Musical Symbol Half Note"},
				{char: "𝅘𝅥", name: "带斜线和符干的二分音符", ename: "Musical Symbol Half Note With Slashed Stem and Flag"},
				{char: "𝅘𝅥𝅮", name: "四分音符", ename: "Musical Symbol Quarter Note"},
				{
					char: "𝅘𝅥𝅯",
					name: "带斜线和符干的四分音符",
					ename: "Musical Symbol Quarter Note With Slashed Stem and Flag"
				},
				{char: "𝅘𝅥𝅰", name: "八分音符", ename: "Musical Symbol Eighth Note"},
				{char: "𝅘𝅥𝅱", name: "十六分音符", ename: "Musical Symbol Sixteenth Note"},
				{char: "𝅘𝅥𝅲", name: "三十二分音符", ename: "Musical Symbol Thirty-Second Note"},
				{char: "𝅥", name: "六十四分音符", ename: "Musical Symbol Sixty-Fourth Note"},
				{char: "𝅦", name: "一百二十八分音符", ename: "Musical Symbol One-Hundred-Twenty-Eighth Note"},
				{char: "𝅧", name: "二百五十六分音符", ename: "Musical Symbol Two-Hundred-Fifty-Sixth Note"},
				{char: "𝅨", name: "五百一十二分音符", ename: "Musical Symbol Five-Hundred-Twelfth Note"},
				{char: "𝅩", name: "一千零二十四分音符", ename: "Musical Symbol One-Thousand-Twenty-Fourth Note"},
				{char: "𝅪", name: "连音符", ename: "Musical Symbol Combining Augmentation Dot"},
				{char: "𝆒", name: "颤音记号", ename: "Musical Symbol Tremolo-1"},
				{char: "𝆓", name: "双颤音记号", ename: "Musical Symbol Tremolo-2"},
				{char: "𝆔", name: "三颤音记号", ename: "Musical Symbol Tremolo-3"},
				{char: "𝆕", name: "琶音上行", ename: "Musical Symbol Arpeggiato Up"},
				{char: "𝆖", name: "琶音下行", ename: "Musical Symbol Arpeggiato Down"},
				{char: "𝆗", name: "断音记号", ename: "Musical Symbol Staccato"},
				{char: "𝆘", name: "特断音记号", ename: "Musical Symbol Staccatissimo"},
				{char: "𝆙", name: "次断音记号", ename: "Musical Symbol Marcato"},
				{char: "𝆚", name: "下方次断音记号", ename: "Musical Symbol Marcato Below"},
				{char: "𝆛", name: "保持音记号", ename: "Musical Symbol Tenuto"},
				{char: "𝆜", name: "保持音断音记号", ename: "Musical Symbol Tenuto Staccato"},
				{char: "𝆝", name: "重音记号", ename: "Musical Symbol Accent"},
				{char: "𝆞", name: "下方重音记号", ename: "Musical Symbol Accent Below"},
				{char: "𝆟", name: "左指拨弦", ename: "Musical Symbol Left-Hand Pizzicato"},
				{char: "𝆠", name: "自然泛音", ename: "Musical Symbol Natural Harmonic"},
				{char: "𝆡", name: "人工泛音", ename: "Musical Symbol Artificial Harmonic"},
				{char: "𝆢", name: "上方 mordent", ename: "Musical Symbol Mordent"},
				{char: "𝆣", name: "下方 mordent", ename: "Musical Symbol Inverted Mordent"},
				{char: "𝆤", name: "回音", ename: "Musical Symbol Turn"},
				{char: "𝆥", name: "倒回音", ename: "Musical Symbol Inverted Turn"},
				{char: "𝆦", name: "颤音", ename: "Musical Symbol Trill"},
				{char: "𝆧", name: "上方颤音", ename: "Musical Symbol Upper Trill"},
				{char: "𝆨", name: "下方颤音", ename: "Musical Symbol Lower Trill"},
				{char: "𝆩", name: "上方普拉勒音", ename: "Musical Symbol Upper Pralltriller"},
				{char: "𝆪", name: "下方普拉勒音", ename: "Musical Symbol Lower Pralltriller"},
				{char: "𝆫", name: "上方普拉勒颤音", ename: "Musical Symbol Upper Pralltriller Trill"},
				{char: "𝆬", name: "下方普拉勒颤音", ename: "Musical Symbol Lower Pralltriller Trill"},
				{char: "𝆭", name: "上方 mordent 颤音", ename: "Musical Symbol Upper Mordent Trill"},
				{char: "𝆮", name: "下方 mordent 颤音", ename: "Musical Symbol Lower Mordent Trill"},
				{char: "𝆯", name: "上方回音颤音", ename: "Musical Symbol Upper Turn Trill"},
				{char: "𝆰", name: "下方回音颤音", ename: "Musical Symbol Lower Turn Trill"},
				{char: "𝆱", name: "上方颤音回音", ename: "Musical Symbol Upper Trill Turn"},
				{char: "𝆲", name: "下方颤音回音", ename: "Musical Symbol Lower Trill Turn"},
				{char: "𝆳", name: "上方普拉勒回音", ename: "Musical Symbol Upper Pralltriller Turn"},
				{char: "𝆴", name: "下方普拉勒回音", ename: "Musical Symbol Lower Pralltriller Turn"},
				{char: "𝆵", name: "上方 mordent 回音", ename: "Musical Symbol Upper Mordent Turn"},
				{char: "𝆶", name: "下方 mordent 回音", ename: "Musical Symbol Lower Mordent Turn"},
				{char: "𝆷", name: "上方回音普拉勒", ename: "Musical Symbol Upper Turn Pralltriller"},
				{char: "𝆸", name: "下方回音普拉勒", ename: "Musical Symbol Lower Turn Pralltriller"},
				{char: "𝆹", name: "上方颤音普拉勒", ename: "Musical Symbol Upper Trill Pralltriller"},
				{char: "𝆺", name: "下方颤音普拉勒", ename: "Musical Symbol Lower Trill Pralltriller"},
				{char: "𝆹𝅥", name: "上方普拉勒颤音普拉勒", ename: "Musical Symbol Upper Pralltriller Pralltriller"},
				{char: "𝆺𝅥", name: "下方普拉勒颤音普拉勒", ename: "Musical Symbol Lower Pralltriller Pralltriller"},
				{char: "𝆹𝅥𝅮", name: "连奏记号", ename: "Musical Symbol Slur"},
				{char: "𝆺𝅥𝅮", name: "连音线", ename: "Musical Symbol Tie"},
				{char: "𝆹𝅥𝅯", name: "连音线下方", ename: "Musical Symbol Tie Below"},
				{char: "𝆺𝅥𝅯", name: "连奏记号下方", ename: "Musical Symbol Slur Below"},
				{char: "𝇁", name: "乐句记号", ename: "Musical Symbol Phrase Mark"},
				{char: "𝇂", name: "乐句记号下方", ename: "Musical Symbol Phrase Mark Below"},
				{char: "𝇃", name: "渐强记号", ename: "Musical Symbol Crescendo"},
				{char: "𝇄", name: "渐弱记号", ename: "Musical Symbol Decrescendo"},
				{char: "𝇅", name: "渐强渐弱记号", ename: "Musical Symbol Crescendo Decrescendo"},
				{char: "𝇆", name: "渐弱渐强记号", ename: "Musical Symbol Decrescendo Crescendo"},
				{char: "𝇇", name: "极弱", ename: "Musical Symbol Pianissimo"},
				{char: "𝇈", name: "弱", ename: "Musical Symbol Piano"},
				{char: "𝇉", name: "中弱", ename: "Musical Symbol Mezzo Piano"},
				{char: "𝇊", name: "中强", ename: "Musical Symbol Mezzo Forte"},
				{char: "𝇋", name: "强", ename: "Musical Symbol Forte"},
				{char: "𝇌", name: "极强", ename: "Musical Symbol Fortissimo"},
				{char: "𝇍", name: "最弱", ename: "Musical Symbol Pianississimo"},
				{char: "𝇎", name: "最强", ename: "Musical Symbol Fortississimo"},
				{char: "𝇏", name: "突弱", ename: "Musical Symbol Sforzando"},
				{char: "𝇐", name: "突强", ename: "Musical Symbol Sforzato"},
				{char: "𝇑", name: "强后突弱", ename: "Musical Symbol Forte Piano"},
				{char: "𝇒", name: "强后即弱", ename: "Musical Symbol Forte-Piano"},
				{char: "𝇓", name: "渐强突弱", ename: "Musical Symbol Crescendo On One Note"},
				{char: "𝇔", name: "渐弱突强", ename: "Musical Symbol Decrescendo On One Note"},
				{char: "𝇕", name: "踏板记号", ename: "Musical Symbol Pedal Mark"},
				{char: "𝇖", name: "释放踏板记号", ename: "Musical Symbol Pedal Up Mark"},
				{char: "𝇗", name: "半踏板记号", ename: "Musical Symbol Half Pedal Mark"},
				{char: "𝇘", name: "持续音踏板记号", ename: "Musical Symbol Sustenuto Pedal Mark"},
				{char: "𝇙", name: "柔音踏板记号", ename: "Musical Symbol Una Corda"},
				{char: "𝇚", name: "三弦踏板记号", ename: "Musical Symbol Tre Corde"},
				{char: "𝇛", name: "制音器上提", ename: "Musical Symbol With Dampers"},
				{char: "𝇜", name: "制音器放下", ename: "Musical Symbol Without Dampers"},
				{char: "𝇝", name: "二连音", ename: "Musical Symbol Duplet"},
				{char: "𝇞", name: "三连音", ename: "Musical Symbol Triplet"},
				{char: "𝇟", name: "四连音", ename: "Musical Symbol Quadruplet"},
				{char: "𝇠", name: "五连音", ename: "Musical Symbol Quintuplet"},
				{char: "𝇡", name: "六连音", ename: "Musical Symbol Sextuplet"},
				{char: "𝇢", name: "七连音", ename: "Musical Symbol Septuplet"},
				{char: "𝇣", name: "八连音", ename: "Musical Symbol Octuplet"},
				{char: "𝇤", name: "九连音", ename: "Musical Symbol Nonuplet"},
				{char: "𝇥", name: "十连音", ename: "Musical Symbol Decuplet"},
				{char: "𝇦", name: "十一连音", ename: "Musical Symbol Undecuplet"},
				{char: "𝇧", name: "十二连音", ename: "Musical Symbol Duodecuplet"},
				{char: "𝇨", name: "十三连音", ename: "Musical Symbol Tredecuplet"},
				{char: "𝇩", name: "十四连音", ename: "Musical Symbol Quattuordecuplet"},
				{char: "𝇪", name: "十五连音", ename: "Musical Symbol Quindecuplet"},
				{char: "♩", name: "四分音符", ename: "Quarter Note", tags: ['音乐', '音符']},
				{char: "♪", name: "八分音符", ename: "Eighth Note", tags: ['音乐', '音符']},
				{char: "♫", name: "连八分音符", ename: "Beamed Eighth Notes", tags: ['音乐', '音符']},
				{char: "♬", name: "连十六分音符", ename: "Beamed Sixteenth Notes", tags: ['音乐', '音符']},
				{char: "♭", name: "降号", ename: "Music Flat Sign", tags: ['音乐', '降号']},
				{char: "♮", name: "还原号", ename: "Music Natural Sign", tags: ['音乐', '还原号']},
				{char: "♯", name: "升号", ename: "Music Sharp Sign", tags: ['音乐', '升号']}
			]
		},
		{
			name: "箭头、方向",
			symbols: [
				{char: "↑", name: "上箭头", ename: "Upwards Arrow"},
				{char: "↓", name: "下箭头", ename: "Downwards Arrow"},
				{char: "←", name: "左箭头", ename: "Leftwards Arrow"},
				{char: "→", name: "右箭头", ename: "Rightwards Arrow"},
				{char: "↖", name: "左上箭头", ename: "North West Arrow"},
				{char: "↗", name: "右上箭头", ename: "North East Arrow"},
				{char: "↘", name: "右下箭头", ename: "South East Arrow"},
				{char: "↙", name: "左下箭头", ename: "South West Arrow"},
				{char: "↔", name: "左右箭头", ename: "Left Right Arrow"},
				{char: "↕", name: "上下箭头", ename: "Up Down Arrow"},
				{char: "⇦", name: "左双箭头", ename: "Leftwards Paired Arrows"},
				{char: "⇧", name: "上双箭头", ename: "Upwards Paired Arrows"},
				{char: "⇨", name: "右双箭头", ename: "Rightwards Paired Arrows"},
				{char: "⇩", name: "下双箭头", ename: "Downwards Paired Arrows"},
				{char: "⇪", name: "caps lock", ename: "Upwards Arrow From Bar"},
				{char: "➔", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➘", name: "右下粗箭头", ename: "Heavy South East Arrow"},
				{char: "➙", name: "右上粗箭头", ename: "Heavy North East Arrow"},
				{char: "➚", name: "右上粗箭头", ename: "Heavy North East Arrow"},
				{char: "➛", name: "右箭头", ename: "Rightwards Arrow"},
				{char: "➜", name: "粗圆头右箭头", ename: "Heavy Round-Tipped Rightwards Arrow"},
				{char: "➝", name: "三角头右箭头", ename: "Triangle-Headed Rightwards Arrow"},
				{char: "➞", name: "粗三角头右箭头", ename: "Heavy Triangle-Headed Rightwards Arrow"},
				{char: "➟", name: "虚线三角头右箭头", ename: "Dashed Triangle-Headed Rightwards Arrow"},
				{char: "➠", name: "粗虚线三角头右箭头", ename: "Heavy Dashed Triangle-Headed Rightwards Arrow"},
				{char: "➡", name: "黑三角右箭头", ename: "Black Rightwards Arrow"},
				{char: "➢", name: "三维顶灯右箭头", ename: "Three-D Top-Lighted Rightwards Arrowhead"},
				{char: "➣", name: "三维底灯右箭头", ename: "Three-D Bottom-Lighted Rightwards Arrowhead"},
				{char: "➤", name: "黑三角", ename: "Black Rightwards Arrowhead"},
				{char: "➥", name: "旋转粗右箭头", ename: "Heavy Rightwards Arrow With Tip Downwards"},
				{char: "➦", name: "圆圈内右箭头", ename: "Rightwards Arrow With Tip Towards Top-Left Corner"},
				{char: "➧", name: "重黑三角", ename: "Heavy Black Curved Upwards and Rightwards Arrow"},
				{char: "➨", name: "曲线右箭头", ename: "Right-Side Arc-Ended Arrow"},
				{char: "➩", name: "曲线粗右箭头", ename: "Heavy Right-Side Arc-Ended Arrow"},
				{char: "➪", name: "曲线三角头右箭头", ename: "Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➫", name: "曲线粗三角头右箭头", ename: "Heavy Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➬", name: "曲线虚线三角头右箭头", ename: "Dashed Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➭", name: "曲线粗虚线三角头右箭头", ename: "Heavy Dashed Triangle-Headed Right-Side Arc-Ended Arrow"},
				{char: "➮", name: "波浪线右箭头", ename: "Wave-Lined Rightwards Arrow"},
				{char: "➯", name: "带垂直笔划的波浪线右箭头", ename: "Wave-Lined Rightwards Arrow With Vertical Stroke"},
				{char: "➱", name: "右上双箭头", ename: "Rightwards Two-Headed Arrow With Vertical Stroke"},
				{char: "➲", name: "粗右上双箭头", ename: "Heavy Rightwards Two-Headed Arrow With Vertical Stroke"},
				{char: "➳", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➴", name: "右下箭头", ename: "Heavy South East Arrow"},
				{char: "➵", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➶", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➷", name: "左下箭头", ename: "Heavy South West Arrow"},
				{char: "➸", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➹", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➺", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➻", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➼", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "➽", name: "右上箭头", ename: "Heavy North East Arrow"},
				{char: "➾", name: "粗右箭头", ename: "Heavy Rightwards Arrow"},
				{char: "☚", name: "黑左指", ename: "Black Left Pointing Index", tags: ['手指', '指向']},
				{char: "☛", name: "黑右指", ename: "Black Right Pointing Index", tags: ['手指', '指向']},
				{char: "☜", name: "白左指", ename: "White Left Pointing Index", tags: ['手指', '指向']},
				{char: "☝", name: "白上指", ename: "White Up Pointing Index", tags: ['手指', '指向']},
				{char: "☞", name: "白右指", ename: "White Right Pointing Index", tags: ['手指', '指向']},
				{char: "☟", name: "白下指", ename: "White Down Pointing Index", tags: ['手指', '指向']},
				{char: "⚞", name: "右聚三线", ename: "Three Lines Converging Right", tags: ['汇聚']},
				{char: "⚟", name: "左聚三线", ename: "Three Lines Converging Left", tags: ['汇聚']}
			]
		}
	]
};