const data = {
	name: "体育",
	groups: [{
		name: "国际象棋",
		symbols: [
			{char: "♔", name: "白国王", ename: "White Chess King", tags: ['国际象棋']},
			{char: "♕", name: "白王后", ename: "White Chess Queen", tags: ['国际象棋']},
			{char: "♖", name: "白战车", ename: "White Chess Rook", tags: ['国际象棋']},
			{char: "♗", name: "白主教", ename: "White Chess Bishop", tags: ['国际象棋']},
			{char: "♘", name: "白骑士", ename: "White Chess Knight", tags: ['国际象棋']},
			{char: "♙", name: "白兵", ename: "White Chess Pawn", tags: ['国际象棋']},
			{char: "♚", name: "黑国王", ename: "Black Chess King", tags: ['国际象棋']},
			{char: "♛", name: "黑王后", ename: "Black Chess Queen", tags: ['国际象棋']},
			{char: "♜", name: "黑战车", ename: "Black Chess Rook", tags: ['国际象棋']},
			{char: "♝", name: "黑主教", ename: "Black Chess Bishop", tags: ['国际象棋']},
			{char: "♞", name: "黑骑士", ename: "Black Chess Knight", tags: ['国际象棋']},
			{char: "♟", name: "黑兵", ename: "Black Chess Pawn", tags: ['国际象棋']},
			{char: "🨀", name: "中性国王", ename: "Neutral Chess King", tags: ['国际象棋']},
			{char: "🨁", name: "中性王后", ename: "Neutral Chess Queen", tags: ['国际象棋']},
			{char: "🨂", name: "中性战车", ename: "Neutral Chess Rook", tags: ['国际象棋']},
			{char: "🨃", name: "中性主教", ename: "Neutral Chess Bishop", tags: ['国际象棋']},
			{char: "🨄", name: "中性骑士", ename: "Neutral Chess Knight", tags: ['国际象棋']},
			{char: "🨅", name: "中性兵", ename: "Neutral Chess Pawn", tags: ['国际象棋']},
			{char: "🨆", name: "白骑士旋转45°", ename: "White Chess Knight Rotated Forty-Five Degrees", tags: ['国际象棋']},
			{char: "🨇", name: "黑骑士旋转45°", ename: "Black Chess Knight Rotated Forty-Five Degrees", tags: ['国际象棋']},
			{
				char: "🨈", name: "中性骑士旋转45°", ename: "Neutral Chess Knight Rotated Forty-Five Degrees", tags: ['国际象棋']
			},
			{char: "🨉", name: "白国王旋转90°", ename: "White Chess King Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨊", name: "白王后旋转90°", ename: "White Chess Queen Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨋", name: "白战车旋转90°", ename: "White Chess Rook Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨌", name: "白主教旋转90°", ename: "White Chess Bishop Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨍", name: "白骑士旋转90°", ename: "White Chess Knight Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨎", name: "白兵旋转90°", ename: "White Chess Pawn Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨏", name: "黑国王旋转90°", ename: "Black Chess King Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨐", name: "黑王后旋转90°", ename: "Black Chess Queen Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨑", name: "黑战车旋转90°", ename: "Black Chess Rook Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨒", name: "黑主教旋转90°", ename: "Black Chess Bishop Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨓", name: "黑骑士旋转90°", ename: "Black Chess Knight Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨔", name: "黑兵旋转90°", ename: "Black Chess Pawn Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨕", name: "中性国王旋转90°", ename: "Neutral Chess King Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨖", name: "中性王后旋转90°", ename: "Neutral Chess Queen Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨗", name: "中性战车旋转90°", ename: "Neutral Chess Rook Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨘", name: "中性主教旋转90°", ename: "Neutral Chess Bishop Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨙", name: "中性骑士旋转90°", ename: "Neutral Chess Knight Rotated Ninety Degrees", tags: ['国际象棋']},
			{char: "🨚", name: "中性兵旋转90°", ename: "Neutral Chess Pawn Rotated Ninety Degrees", tags: ['国际象棋']},
			{
				char: "🨛", name: "白骑士旋转135°", ename: "White Chess Knight Rotated One Hundred Thirty-Five Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨜", name: "黑骑士旋转135°", ename: "Black Chess Knight Rotated One Hundred Thirty-Five Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨝", name: "中性骑士旋转135°", ename: "Neutral Chess Knight Rotated One Hundred Thirty-Five Degrees",
				tags: ['国际象棋']
			},
			{char: "🨞", name: "白国王镜像", ename: "White Chess Turned King", tags: ['国际象棋']},
			{char: "🨟", name: "白王后镜像", ename: "White Chess Turned Queen", tags: ['国际象棋']},
			{char: "🨠", name: "白战车镜像", ename: "White Chess Turned Rook", tags: ['国际象棋']},
			{char: "🨡", name: "白主教镜像", ename: "White Chess Turned Bishop", tags: ['国际象棋']},
			{char: "🨢", name: "白骑士镜像", ename: "White Chess Turned Knight", tags: ['国际象棋']},
			{char: "🨣", name: "白兵镜像", ename: "White Chess Turned Pawn", tags: ['国际象棋']},
			{char: "🨤", name: "黑国王镜像", ename: "Black Chess Turned King", tags: ['国际象棋']},
			{char: "🨥", name: "黑王后镜像", ename: "Black Chess Turned Queen", tags: ['国际象棋']},
			{char: "🨦", name: "黑战车镜像", ename: "Black Chess Turned Rook", tags: ['国际象棋']},
			{char: "🨧", name: "黑主教镜像", ename: "Black Chess Turned Bishop", tags: ['国际象棋']},
			{char: "🨨", name: "黑骑士镜像", ename: "Black Chess Turned Knight", tags: ['国际象棋']},
			{char: "🨩", name: "黑兵镜像", ename: "Black Chess Turned Pawn", tags: ['国际象棋']},
			{char: "🨪", name: "中性国王镜像", ename: "Neutral Chess Turned King", tags: ['国际象棋']},
			{char: "🨫", name: "中性王后镜像", ename: "Neutral Chess Turned Queen", tags: ['国际象棋']},
			{char: "🨬", name: "中性战车镜像", ename: "Neutral Chess Turned Rook", tags: ['国际象棋']},
			{char: "🨭", name: "中性主教镜像", ename: "Neutral Chess Turned Bishop", tags: ['国际象棋']},
			{char: "🨮", name: "中性骑士镜像", ename: "Neutral Chess Turned Knight", tags: ['国际象棋']},
			{char: "🨯", name: "中性兵镜像", ename: "Neutral Chess Turned Pawn", tags: ['国际象棋']},
			{
				char: "🨰",
				name: "白骑士旋转225°",
				ename: "White Chess Knight Rotated Two Hundred Twenty-Five Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨱",
				name: "黑骑士旋转225°",
				ename: "Black Chess Knight Rotated Two Hundred Twenty-Five Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨲",
				name: "中性骑士旋转225°",
				ename: "Neutral Chess Knight Rotated Two Hundred Twenty-Five Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨳",
				name: "白国王旋转270°",
				ename: "White Chess King Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨴",
				name: "白王后旋转270°",
				ename: "White Chess Queen Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨵",
				name: "白战车旋转270°",
				ename: "White Chess Rook Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨶",
				name: "白主教旋转270°",
				ename: "White Chess Bishop Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨷",
				name: "白骑士旋转270°",
				ename: "White Chess Knight Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨸",
				name: "白兵旋转270°",
				ename: "White Chess Pawn Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨹",
				name: "黑国王旋转270°",
				ename: "Black Chess King Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨺",
				name: "黑王后旋转270°",
				ename: "Black Chess Queen Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨻",
				name: "黑战车旋转270°",
				ename: "Black Chess Rook Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨼",
				name: "黑主教旋转270°",
				ename: "Black Chess Bishop Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨽",
				name: "黑骑士旋转270°",
				ename: "Black Chess Knight Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨾",
				name: "黑兵旋转270°",
				ename: "Black Chess Pawn Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🨿",
				name: "中性国王旋转270°",
				ename: "Neutral Chess King Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩀",
				name: "中性王后旋转270°",
				ename: "Neutral Chess Queen Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩁",
				name: "中性战车旋转270°",
				ename: "Neutral Chess Rook Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩂",
				name: "中性主教旋转270°",
				ename: "Neutral Chess Bishop Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩃",
				name: "中性骑士旋转270°",
				ename: "Neutral Chess Knight Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩄",
				name: "中性兵旋转270°",
				ename: "Neutral Chess Pawn Rotated Two Hundred Seventy Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩅",
				name: "白骑士旋转315°",
				ename: "White Chess Knight Rotated Three Hundred Fifteen Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩆",
				name: "黑骑士旋转315°",
				ename: "Black Chess Knight Rotated Three Hundred Fifteen Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩇",
				name: "中性骑士旋转315°",
				ename: "Neutral Chess Knight Rotated Three Hundred Fifteen Degrees",
				tags: ['国际象棋']
			},
			{char: "🩈", name: "白等跳马", ename: "White Chess Equihopper", tags: ['国际象棋']},
			{char: "🩉", name: "黑等跳马", ename: "Black Chess Equihopper", tags: ['国际象棋']},
			{char: "🩊", name: "中性等跳马", ename: "Neutral Chess Equihopper", tags: ['国际象棋']},
			{
				char: "🩋",
				name: "白等跳马旋转90°",
				ename: "White Chess Equihopper Rotated Ninety Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩌",
				name: "黑等跳马旋转90°",
				ename: "Black Chess Equihopper Rotated Ninety Degrees",
				tags: ['国际象棋']
			},
			{
				char: "🩍",
				name: "中性等跳马旋转90°",
				ename: "Neutral Chess Equihopper Rotated Ninety Degrees",
				tags: ['国际象棋']
			},
			{char: "🩎", name: "白骑士王后", ename: "White Chess Knight-Queen", tags: ['国际象棋']},
			{char: "🩏", name: "白骑士战车", ename: "White Chess Knight-Rook", tags: ['国际象棋']},
			{char: "🩐", name: "白骑士主教", ename: "White Chess Knight-Bishop", tags: ['国际象棋']},
			{char: "🩑", name: "黑骑士王后", ename: "Black Chess Knight-Queen", tags: ['国际象棋']},
			{char: "🩒", name: "黑骑士战车", ename: "Black Chess Knight-Rook", tags: ['国际象棋']},
			{char: "🩓", name: "黑骑士主教", ename: "Black Chess Knight-Bishop", tags: ['国际象棋']}
		]
	},
		{
			name: "中国象棋",
			symbols: [
				{char: "🩠", name: "红帅", ename: "Xiangqi Red General", tags: ['中国象棋']},
				{char: "🩡", name: "红仕", ename: "Xiangqi Red Mandarin", tags: ['中国象棋']},
				{char: "🩢", name: "红相", ename: "Xiangqi Red Elephant", tags: ['中国象棋']},
				{char: "🩣", name: "红马", ename: "Xiangqi Red Horse", tags: ['中国象棋']},
				{char: "🩤", name: "红车", ename: "Xiangqi Red Chariot", tags: ['中国象棋']},
				{char: "🩥", name: "红炮", ename: "Xiangqi Red Cannon", tags: ['中国象棋']},
				{char: "🩦", name: "红兵", ename: "Xiangqi Red Soldier", tags: ['中国象棋']},
				{char: "🩧", name: "黑将", ename: "Xiangqi Black General", tags: ['中国象棋']},
				{char: "🩨", name: "黑士", ename: "Xiangqi Black Mandarin", tags: ['中国象棋']},
				{char: "🩩", name: "黑象", ename: "Xiangqi Black Elephant", tags: ['中国象棋']},
				{char: "🩪", name: "黑马", ename: "Xiangqi Black Horse", tags: ['中国象棋']},
				{char: "🩫", name: "黑车", ename: "Xiangqi Black Chariot", tags: ['中国象棋']},
				{char: "🩬", name: "黑炮", ename: "Xiangqi Black Cannon", tags: ['中国象棋']},
				{char: "🩭", name: "黑卒", ename: "Xiangqi Black Soldier", tags: ['中国象棋']}
			]
		},
		{
			name: "扑克牌",
			symbols: [
				{char: "🂡", name: "黑桃A", ename: "Playing Card Ace of Spades"},
				{char: "🂢", name: "黑桃2", ename: "Playing Card Two of Spades"},
				{char: "🂣", name: "黑桃3", ename: "Playing Card Three of Spades"},
				{char: "🂤", name: "黑桃4", ename: "Playing Card Four of Spades"},
				{char: "🂥", name: "黑桃5", ename: "Playing Card Five of Spades"},
				{char: "🂦", name: "黑桃6", ename: "Playing Card Six of Spades"},
				{char: "🂧", name: "黑桃7", ename: "Playing Card Seven of Spades"},
				{char: "🂨", name: "黑桃8", ename: "Playing Card Eight of Spades"},
				{char: "🂩", name: "黑桃9", ename: "Playing Card Nine of Spades"},
				{char: "🂪", name: "黑桃10", ename: "Playing Card Ten of Spades"},
				{char: "🂫", name: "黑桃J", ename: "Playing Card Jack of Spades"},
				{char: "🂭", name: "黑桃Q", ename: "Playing Card Queen of Spades"},
				{char: "🂮", name: "黑桃K", ename: "Playing Card King of Spades"},
				{char: "🂬", name: "黑桃骑士", ename: "Playing Card Knight of Spades"},

				{char: "🂱", name: "红心A", ename: "Playing Card Ace of Hearts"},
				{char: "🂲", name: "红心2", ename: "Playing Card Two of Hearts"},
				{char: "🂳", name: "红心3", ename: "Playing Card Three of Hearts"},
				{char: "🂴", name: "红心4", ename: "Playing Card Four of Hearts"},
				{char: "🂵", name: "红心5", ename: "Playing Card Five of Hearts"},
				{char: "🂶", name: "红心6", ename: "Playing Card Six of Hearts"},
				{char: "🂷", name: "红心7", ename: "Playing Card Seven of Hearts"},
				{char: "🂸", name: "红心8", ename: "Playing Card Eight of Hearts"},
				{char: "🂹", name: "红心9", ename: "Playing Card Nine of Hearts"},
				{char: "🂺", name: "红心10", ename: "Playing Card Ten of Hearts"},
				{char: "🂻", name: "红心J", ename: "Playing Card Jack of Hearts"},
				{char: "🂽", name: "红心Q", ename: "Playing Card Queen of Hearts"},
				{char: "🂾", name: "红心K", ename: "Playing Card King of Hearts"},
				{char: "🂼", name: "红心骑士", ename: "Playing Card Knight of Hearts"},

				{char: "🃑", name: "梅花A", ename: "Playing Card Ace of Clubs"},
				{char: "🃒", name: "梅花2", ename: "Playing Card Two of Clubs"},
				{char: "🃓", name: "梅花3", ename: "Playing Card Three of Clubs"},
				{char: "🃔", name: "梅花4", ename: "Playing Card Four of Clubs"},
				{char: "🃕", name: "梅花5", ename: "Playing Card Five of Clubs"},
				{char: "🃖", name: "梅花6", ename: "Playing Card Six of Clubs"},
				{char: "🃗", name: "梅花7", ename: "Playing Card Seven of Clubs"},
				{char: "🃘", name: "梅花8", ename: "Playing Card Eight of Clubs"},
				{char: "🃙", name: "梅花9", ename: "Playing Card Nine of Clubs"},
				{char: "🃚", name: "梅花10", ename: "Playing Card Ten of Clubs"},
				{char: "🃛", name: "梅花J", ename: "Playing Card Jack of Clubs"},
				{char: "🃝", name: "梅花Q", ename: "Playing Card Queen of Clubs"},
				{char: "🃞", name: "梅花K", ename: "Playing Card King of Clubs"},
				{char: "🃜", name: "梅花骑士", ename: "Playing Card Knight of Clubs"},

				{char: "🃁", name: "方块A", ename: "Playing Card Ace of Diamonds"},
				{char: "🃂", name: "方块2", ename: "Playing Card Two of Diamonds"},
				{char: "🃃", name: "方块3", ename: "Playing Card Three of Diamonds"},
				{char: "🃄", name: "方块4", ename: "Playing Card Four of Diamonds"},
				{char: "🃅", name: "方块5", ename: "Playing Card Five of Diamonds"},
				{char: "🃆", name: "方块6", ename: "Playing Card Six of Diamonds"},
				{char: "🃇", name: "方块7", ename: "Playing Card Seven of Diamonds"},
				{char: "🃈", name: "方块8", ename: "Playing Card Eight of Diamonds"},
				{char: "🃉", name: "方块9", ename: "Playing Card Nine of Diamonds"},
				{char: "🃊", name: "方块10", ename: "Playing Card Ten of Diamonds"},
				{char: "🃋", name: "方块J", ename: "Playing Card Jack of Diamonds"},
				{char: "🃍", name: "方块Q", ename: "Playing Card Queen of Diamonds"},
				{char: "🃎", name: "方块K", ename: "Playing Card King of Diamonds"},
				{char: "🃌", name: "方块骑士", ename: "Playing Card Knight of Diamonds"},

				{char: "🃏", name: "黑小丑", ename: "Playing Card Black Joker", tags: ['百搭', '鬼牌', '王牌']},
				{char: "🃟", name: "白小丑", ename: "Playing Card White Joker"},
				{char: "🂿", name: "红小丑（第三王）", ename: "Playing Card Red Joker(used as the third joker)"},

				{char: "♠", name: "黑桃", ename: "Black Spade Suit"},
				{char: "♡", name: "红心", ename: "White Heart Suit"},
				{char: "♢", name: "方块", ename: "White Diamond Suit"},
				{char: "♣", name: "梅花", ename: "Black Club Suit"},
				{char: "♤", name: "反色黑桃", ename: "White Spade Suit"},
				{char: "♥", name: "反色红心", ename: "Red Heart Suit"},
				{char: "♧", name: "反色梅花", ename: "White Club Suit"},
				{char: "♦", name: "反色方块", ename: "Red Diamond Suit"},

				{char: '🂠', name: "牌背", ename: "PLAYING CARD FOOL"},

				{char: "🃠", name: "傻瓜", ename: "PLAYING CARD FOOL"},
				{char: "🃡", name: "个人", ename: "PLAYING CARD TRUMP-01 individual"},
				{char: "🃵", name: "集体", ename: "Playing Card Back 21 collective"},
				{char: "🃢", name: "童年", ename: "PLAYING CARD TRUMP-02 childhood"},
				{char: "🃣", name: "少年", ename: "PLAYING CARD TRUMP-03 youth"},
				{char: "🃤", name: "成年", ename: "PLAYING CARD TRUMP-04 maturity"},
				{char: "🃥", name: "老年", ename: "PLAYING CARD TRUMP-05 old age"},
				{char: "🃦", name: "早上", ename: "PLAYING CARD TRUMP-06 morning"},
				{char: "🃧", name: "下午", ename: "PLAYING CARD TRUMP-07 afternoon"},
				{char: "🃨", name: "晚上", ename: "PLAYING CARD TRUMP-08 evening"},
				{char: "🃩", name: "夜晚", ename: "PLAYING CARD TRUMP-09 night"},
				{char: "🃪", name: "土风（四元素之二）", ename: "PLAYING CARD TRUMP-10 earth and air"},
				{char: "🃫", name: "水火（四元素之二）", ename: "PLAYING CARD TRUMP-11 water and fire"},
				{char: "🃬", name: "跳舞", ename: "PLAYING CARD TRUMP-12 dance"},
				{char: "🃭", name: "购物", ename: "PLAYING CARD TRUMP-13 shopping"},
				{char: "🃮", name: "户外", ename: "PLAYING CARD TRUMP-14 open air"},
				{char: "🃯", name: "视觉艺术", ename: "PLAYING CARD TRUMP-15 visual arts"},
				{char: "🃰", name: "春", ename: "PLAYING CARD TRUMP-16 spring"},
				{char: "🃱", name: "夏", ename: "PLAYING CARD TRUMP-17 summer"},
				{char: "🃲", name: "秋", ename: "PLAYING CARD TRUMP-18 autumn"},
				{char: "🃳", name: "冬", ename: "PLAYING CARD TRUMP-19 winter"},
				{char: "🃴", name: "牌局", ename: "Playing Card Back 20 the game"}
			]
		},
		{
			name: "麻将",
			symbols: [
				{char: "🀀", name: "东风", ename: "Mahjong Tile East Wind", tags: ['麻将牌']},
				{char: "🀁", name: "南风", ename: "Mahjong Tile South Wind", tags: ['麻将牌']},
				{char: "🀂", name: "西风", ename: "Mahjong Tile West Wind", tags: ['麻将牌']},
				{char: "🀃", name: "北风", ename: "Mahjong Tile North Wind", tags: ['麻将牌']},
				{char: "🀄", name: "红中", ename: "Mahjong Tile Red Dragon", tags: ['麻将牌']},
				{char: "🀅", name: "发财", ename: "Mahjong Tile Green Dragon", tags: ['麻将牌']},
				{char: "🀆", name: "白板", ename: "Mahjong Tile White Dragon", tags: ['麻将牌']},
				{char: "🀇", name: "一万", ename: "Mahjong Tile One of Characters", tags: ['麻将牌']},
				{char: "🀈", name: "二万", ename: "Mahjong Tile Two of Characters", tags: ['麻将牌']},
				{char: "🀉", name: "三万", ename: "Mahjong Tile Three of Characters", tags: ['麻将牌']},
				{char: "🀊", name: "四万", ename: "Mahjong Tile Four of Characters", tags: ['麻将牌']},
				{char: "🀋", name: "五万", ename: "Mahjong Tile Five of Characters", tags: ['麻将牌']},
				{char: "🀌", name: "六万", ename: "Mahjong Tile Six of Characters", tags: ['麻将牌']},
				{char: "🀍", name: "七万", ename: "Mahjong Tile Seven of Characters", tags: ['麻将牌']},
				{char: "🀎", name: "八万", ename: "Mahjong Tile Eight of Characters", tags: ['麻将牌']},
				{char: "🀏", name: "九万", ename: "Mahjong Tile Nine of Characters", tags: ['麻将牌']},
				{char: "🀐", name: "一索", ename: "Mahjong Tile One of Bamboos", tags: ['麻将牌', '一条', '麻雀']},
				{char: "🀑", name: "二索", ename: "Mahjong Tile Two of Bamboos", tags: ['麻将牌', '二条']},
				{char: "🀒", name: "三索", ename: "Mahjong Tile Three of Bamboos", tags: ['麻将牌', '三条']},
				{char: "🀓", name: "四索", ename: "Mahjong Tile Four of Bamboos", tags: ['麻将牌', '四条']},
				{char: "🀔", name: "五索", ename: "Mahjong Tile Five of Bamboos", tags: ['麻将牌', '五条']},
				{char: "🀕", name: "六索", ename: "Mahjong Tile Six of Bamboos", tags: ['麻将牌', '六条']},
				{char: "🀖", name: "七索", ename: "Mahjong Tile Seven of Bamboos", tags: ['麻将牌', '七条']},
				{char: "🀗", name: "八索", ename: "Mahjong Tile Eight of Bamboos", tags: ['麻将牌', '八条']},
				{char: "🀘", name: "九索", ename: "Mahjong Tile Nine of Bamboos", tags: ['麻将牌', '九条']},
				{char: "🀙", name: "一筒", ename: "Mahjong Tile One of Circles", tags: ['麻将牌', '一饼']},
				{char: "🀚", name: "二筒", ename: "Mahjong Tile Two of Circles", tags: ['麻将牌', '二饼']},
				{char: "🀛", name: "三筒", ename: "Mahjong Tile Three of Circles", tags: ['麻将牌', '三饼']},
				{char: "🀜", name: "四筒", ename: "Mahjong Tile Four of Circles", tags: ['麻将牌', '四饼']},
				{char: "🀝", name: "五筒", ename: "Mahjong Tile Five of Circles", tags: ['麻将牌', '五饼']},
				{char: "🀞", name: "六筒", ename: "Mahjong Tile Six of Circles", tags: ['麻将牌', '六饼']},
				{char: "🀟", name: "七筒", ename: "Mahjong Tile Seven of Circles", tags: ['麻将牌', '七饼']},
				{char: "🀠", name: "八筒", ename: "Mahjong Tile Eight of Circles", tags: ['麻将牌', '八饼']},
				{char: "🀡", name: "九筒", ename: "Mahjong Tile Nine of Circles", tags: ['麻将牌', '九饼']},
				{char: "🀦", name: "梅", ename: "Mahjong Tile Plum", tags: ['麻将牌']},
				{char: "🀧", name: "兰", ename: "Mahjong Tile Orchid", tags: ['麻将牌']},
				{char: "🀨", name: "竹", ename: "Mahjong Tile Bamboo", tags: ['麻将牌']},
				{char: "🀩", name: "菊", ename: "Mahjong Tile Chrysanthemum", tags: ['麻将牌']},
				{char: "🀢", name: "春", ename: "Mahjong Tile Spring", tags: ['麻将牌']},
				{char: "🀣", name: "夏", ename: "Mahjong Tile Summer", tags: ['麻将牌']},
				{char: "🀤", name: "秋", ename: "Mahjong Tile Autumn", tags: ['麻将牌']},
				{char: "🀥", name: "冬", ename: "Mahjong Tile Winter", tags: ['麻将牌']},
				{char: "🀪", name: "百搭", ename: "Mahjong Tile Joker", tags: ['麻将牌']},
				{char: "🀫", name: "背面", ename: "Mahjong Tile Back", tags: ['麻将牌']}
			]
		},
		{
			name: "骰子/色子",
			symbols: [
				{char: "⚀", name: "1点", ename: "Die Face-1"},
				{char: "⚁", name: "2点", ename: "Die Face-2"},
				{char: "⚂", name: "3点", ename: "Die Face-3"},
				{char: "⚃", name: "4点", ename: "Die Face-4"},
				{char: "⚄", name: "5点", ename: "Die Face-5"},
				{char: "⚅", name: "6点", ename: "Die Face-6"}
			]
		},
		{
			name: "多米诺骨牌",
			symbols: [
				{char: '🀰', name: '水平骨牌背面', ename: 'DOMINO TILE HORIZONTAL BACK'},
				{char: '🀱', name: '水平骨牌 0-0', ename: 'DOMINO TILE HORIZONTAL-00-00'},
				{char: '🀲', name: '水平骨牌 0-1', ename: 'DOMINO TILE HORIZONTAL-00-01'},
				{char: '🀳', name: '水平骨牌 0-2', ename: 'DOMINO TILE HORIZONTAL-00-02'},
				{char: '🀴', name: '水平骨牌 0-3', ename: 'DOMINO TILE HORIZONTAL-00-03'},
				{char: '🀵', name: '水平骨牌 0-4', ename: 'DOMINO TILE HORIZONTAL-00-04'},
				{char: '🀶', name: '水平骨牌 0-5', ename: 'DOMINO TILE HORIZONTAL-00-05'},
				{char: '🀷', name: '水平骨牌 0-6', ename: 'DOMINO TILE HORIZONTAL-00-06'},
				{char: '🀸', name: '水平骨牌 1-0', ename: 'DOMINO TILE HORIZONTAL-01-00'},
				{char: '🀹', name: '水平骨牌 1-1', ename: 'DOMINO TILE HORIZONTAL-01-01'},
				{char: '🀺', name: '水平骨牌 1-2', ename: 'DOMINO TILE HORIZONTAL-01-02'},
				{char: '🀻', name: '水平骨牌 1-3', ename: 'DOMINO TILE HORIZONTAL-01-03'},
				{char: '🀼', name: '水平骨牌 1-4', ename: 'DOMINO TILE HORIZONTAL-01-04'},
				{char: '🀽', name: '水平骨牌 1-5', ename: 'DOMINO TILE HORIZONTAL-01-05'},
				{char: '🀾', name: '水平骨牌 1-6', ename: 'DOMINO TILE HORIZONTAL-01-06'},
				{char: '🀿', name: '水平骨牌 2-0', ename: 'DOMINO TILE HORIZONTAL-02-00'},
				{char: '🁀', name: '水平骨牌 2-1', ename: 'DOMINO TILE HORIZONTAL-02-01'},
				{char: '🁁', name: '水平骨牌 2-2', ename: 'DOMINO TILE HORIZONTAL-02-02'},
				{char: '🁂', name: '水平骨牌 2-3', ename: 'DOMINO TILE HORIZONTAL-02-03'},
				{char: '🁃', name: '水平骨牌 2-4', ename: 'DOMINO TILE HORIZONTAL-02-04'},
				{char: '🁄', name: '水平骨牌 2-5', ename: 'DOMINO TILE HORIZONTAL-02-05'},
				{char: '🁅', name: '水平骨牌 2-6', ename: 'DOMINO TILE HORIZONTAL-02-06'},
				{char: '🁆', name: '水平骨牌 3-0', ename: 'DOMINO TILE HORIZONTAL-03-00'},
				{char: '🁇', name: '水平骨牌 3-1', ename: 'DOMINO TILE HORIZONTAL-03-01'},
				{char: '🁈', name: '水平骨牌 3-2', ename: 'DOMINO TILE HORIZONTAL-03-02'},
				{char: '🁉', name: '水平骨牌 3-3', ename: 'DOMINO TILE HORIZONTAL-03-03'},
				{char: '🁊', name: '水平骨牌 3-4', ename: 'DOMINO TILE HORIZONTAL-03-04'},
				{char: '🁋', name: '水平骨牌 3-5', ename: 'DOMINO TILE HORIZONTAL-03-05'},
				{char: '🁌', name: '水平骨牌 3-6', ename: 'DOMINO TILE HORIZONTAL-03-06'},
				{char: '🁍', name: '水平骨牌 4-0', ename: 'DOMINO TILE HORIZONTAL-04-00'},
				{char: '🁎', name: '水平骨牌 4-1', ename: 'DOMINO TILE HORIZONTAL-04-01'},
				{char: '🁏', name: '水平骨牌 4-2', ename: 'DOMINO TILE HORIZONTAL-04-02'},
				{char: '🁐', name: '水平骨牌 4-3', ename: 'DOMINO TILE HORIZONTAL-04-03'},
				{char: '🁑', name: '水平骨牌 4-4', ename: 'DOMINO TILE HORIZONTAL-04-04'},
				{char: '🁒', name: '水平骨牌 4-5', ename: 'DOMINO TILE HORIZONTAL-04-05'},
				{char: '🁓', name: '水平骨牌 4-6', ename: 'DOMINO TILE HORIZONTAL-04-06'},
				{char: '🁔', name: '水平骨牌 5-0', ename: 'DOMINO TILE HORIZONTAL-05-00'},
				{char: '🁕', name: '水平骨牌 5-1', ename: 'DOMINO TILE HORIZONTAL-05-01'},
				{char: '🁖', name: '水平骨牌 5-2', ename: 'DOMINO TILE HORIZONTAL-05-02'},
				{char: '🁗', name: '水平骨牌 5-3', ename: 'DOMINO TILE HORIZONTAL-05-03'},
				{char: '🁘', name: '水平骨牌 5-4', ename: 'DOMINO TILE HORIZONTAL-05-04'},
				{char: '🁙', name: '水平骨牌 5-5', ename: 'DOMINO TILE HORIZONTAL-05-05'},
				{char: '🁚', name: '水平骨牌 5-6', ename: 'DOMINO TILE HORIZONTAL-05-06'},
				{char: '🁛', name: '水平骨牌 6-0', ename: 'DOMINO TILE HORIZONTAL-06-00'},
				{char: '🁜', name: '水平骨牌 6-1', ename: 'DOMINO TILE HORIZONTAL-06-01'},
				{char: '🁝', name: '水平骨牌 6-2', ename: 'DOMINO TILE HORIZONTAL-06-02'},
				{char: '🁞', name: '水平骨牌 6-3', ename: 'DOMINO TILE HORIZONTAL-06-03'},
				{char: '🁟', name: '水平骨牌 6-4', ename: 'DOMINO TILE HORIZONTAL-06-04'},
				{char: '🁠', name: '水平骨牌 6-5', ename: 'DOMINO TILE HORIZONTAL-06-05'},
				{char: '🁡', name: '水平骨牌 6-6', ename: 'DOMINO TILE HORIZONTAL-06-06'},
				{char: '🁢', name: '垂直骨牌背面', ename: 'DOMINO TILE VERTICAL BACK'},
				{char: '🁣', name: '垂直骨牌 0-0', ename: 'DOMINO TILE VERTICAL-00-00'},
				{char: '🁤', name: '垂直骨牌 0-1', ename: 'DOMINO TILE VERTICAL-00-01'},
				{char: '🁥', name: '垂直骨牌 0-2', ename: 'DOMINO TILE VERTICAL-00-02'},
				{char: '🁦', name: '垂直骨牌 0-3', ename: 'DOMINO TILE VERTICAL-00-03'},
				{char: '🁧', name: '垂直骨牌 0-4', ename: 'DOMINO TILE VERTICAL-00-04'},
				{char: '🁨', name: '垂直骨牌 0-5', ename: 'DOMINO TILE VERTICAL-00-05'},
				{char: '🁩', name: '垂直骨牌 0-6', ename: 'DOMINO TILE VERTICAL-00-06'},
				{char: '🁪', name: '垂直骨牌 1-0', ename: 'DOMINO TILE VERTICAL-01-00'},
				{char: '🁫', name: '垂直骨牌 1-1', ename: 'DOMINO TILE VERTICAL-01-01'},
				{char: '🁬', name: '垂直骨牌 1-2', ename: 'DOMINO TILE VERTICAL-01-02'},
				{char: '🁭', name: '垂直骨牌 1-3', ename: 'DOMINO TILE VERTICAL-01-03'},
				{char: '🁮', name: '垂直骨牌 1-4', ename: 'DOMINO TILE VERTICAL-01-04'},
				{char: '🁯', name: '垂直骨牌 1-5', ename: 'DOMINO TILE VERTICAL-01-05'},
				{char: '🁰', name: '垂直骨牌 1-6', ename: 'DOMINO TILE VERTICAL-01-06'},
				{char: '🁱', name: '垂直骨牌 2-0', ename: 'DOMINO TILE VERTICAL-02-00'},
				{char: '🁲', name: '垂直骨牌 2-1', ename: 'DOMINO TILE VERTICAL-02-01'},
				{char: '🁳', name: '垂直骨牌 2-2', ename: 'DOMINO TILE VERTICAL-02-02'},
				{char: '🁴', name: '垂直骨牌 2-3', ename: 'DOMINO TILE VERTICAL-02-03'},
				{char: '🁵', name: '垂直骨牌 2-4', ename: 'DOMINO TILE VERTICAL-02-04'},
				{char: '🁶', name: '垂直骨牌 2-5', ename: 'DOMINO TILE VERTICAL-02-05'},
				{char: '🁷', name: '垂直骨牌 2-6', ename: 'DOMINO TILE VERTICAL-02-06'},
				{char: '🁸', name: '垂直骨牌 3-0', ename: 'DOMINO TILE VERTICAL-03-00'},
				{char: '🁹', name: '垂直骨牌 3-1', ename: 'DOMINO TILE VERTICAL-03-01'},
				{char: '🁺', name: '垂直骨牌 3-2', ename: 'DOMINO TILE VERTICAL-03-02'},
				{char: '🁻', name: '垂直骨牌 3-3', ename: 'DOMINO TILE VERTICAL-03-03'},
				{char: '🁼', name: '垂直骨牌 3-4', ename: 'DOMINO TILE VERTICAL-03-04'},
				{char: '🁽', name: '垂直骨牌 3-5', ename: 'DOMINO TILE VERTICAL-03-05'},
				{char: '🁾', name: '垂直骨牌 3-6', ename: 'DOMINO TILE VERTICAL-03-06'},
				{char: '🁿', name: '垂直骨牌 4-0', ename: 'DOMINO TILE VERTICAL-04-00'},
				{char: '🂀', name: '垂直骨牌 4-1', ename: 'DOMINO TILE VERTICAL-04-01'},
				{char: '🂁', name: '垂直骨牌 4-2', ename: 'DOMINO TILE VERTICAL-04-02'},
				{char: '🂂', name: '垂直骨牌 4-3', ename: 'DOMINO TILE VERTICAL-04-03'},
				{char: '🂃', name: '垂直骨牌 4-4', ename: 'DOMINO TILE VERTICAL-04-04'},
				{char: '🂄', name: '垂直骨牌 4-5', ename: 'DOMINO TILE VERTICAL-04-05'},
				{char: '🂅', name: '垂直骨牌 4-6', ename: 'DOMINO TILE VERTICAL-04-06'},
				{char: '🂆', name: '垂直骨牌 5-0', ename: 'DOMINO TILE VERTICAL-05-00'},
				{char: '🂇', name: '垂直骨牌 5-1', ename: 'DOMINO TILE VERTICAL-05-01'},
				{char: '🂈', name: '垂直骨牌 5-2', ename: 'DOMINO TILE VERTICAL-05-02'},
				{char: '🂉', name: '垂直骨牌 5-3', ename: 'DOMINO TILE VERTICAL-05-03'},
				{char: '🂊', name: '垂直骨牌 5-4', ename: 'DOMINO TILE VERTICAL-05-04'},
				{char: '🂋', name: '垂直骨牌 5-5', ename: 'DOMINO TILE VERTICAL-05-05'},
				{char: '🂌', name: '垂直骨牌 5-6', ename: 'DOMINO TILE VERTICAL-05-06'},
				{char: '🂍', name: '垂直骨牌 6-0', ename: 'DOMINO TILE VERTICAL-06-00'},
				{char: '🂎', name: '垂直骨牌 6-1', ename: 'DOMINO TILE VERTICAL-06-01'},
				{char: '🂏', name: '垂直骨牌 6-2', ename: 'DOMINO TILE VERTICAL-06-02'},
				{char: '🂐', name: '垂直骨牌 6-3', ename: 'DOMINO TILE VERTICAL-06-03'},
				{char: '🂑', name: '垂直骨牌 6-4', ename: 'DOMINO TILE VERTICAL-06-04'},
				{char: '🂒', name: '垂直骨牌 6-5', ename: 'DOMINO TILE VERTICAL-06-05'},
				{char: '🂓', name: '垂直骨牌 6-6', ename: 'DOMINO TILE VERTICAL-06-06'}
			]
		},
		{
			name: '其他',
			symbols: [
				{char: "⚽", name: "足球", ename: "Soccer Ball", tags: ['足球', '运动']},
				{char: "⚾", name: "棒球", ename: "Baseball", tags: ['棒球', '运动']},
				{char: "🏀", name: "篮球", ename: "Basketball"},
				{char: "🏐", name: "排球", ename: "Volleyball"},
				{char: "🏈", name: "橄榄球", ename: "American Football"},
				{char: "🏉", name: "英式橄榄球", ename: "Rugby Football"},
				{char: "🎾", name: "网球", ename: "Tennis"},
				{char: "🎳", name: "保龄球", ename: "Bowling"},
				{char: "🏏", name: "板球", ename: "Cricket Game"},
				{char: "🏑", name: "曲棍球", ename: "Field Hockey"},
				{char: "🏒", name: "冰球", ename: "Ice Hockey"},
				{char: "🏓", name: "乒乓球", ename: "Ping Pong"},
				{char: "🏸", name: "羽毛球", ename: "Badminton"},
				{char: "🥊", name: "拳击手套", ename: "Boxing Glove"},
				{char: "🥋", name: "武术服", ename: "Martial Arts Uniform"},
				{char: "🥅", name: "球门", ename: "Goal Net"},
				{char: "🥇", name: "金牌", ename: "1st Place Medal"},
				{char: "🥈", name: "银牌", ename: "2nd Place Medal"},
				{char: "🥉", name: "铜牌", ename: "3rd Place Medal"},
				{char: "🏆", name: "奖杯", ename: "Trophy"},
				{char: "🎯", name: "靶心", ename: "Direct Hit"},
				{char: "⛷", name: "滑雪者", ename: "Skier", tags: ['滑雪', '运动']},
				{char: "⛸", name: "冰鞋", ename: "Ice Skate", tags: ['冰鞋', '运动']},
				{char: "⛵", name: "帆船", ename: "Sailboat", tags: []},
				{char: "⛀", name: "白跳棋", ename: "White Draughts Man", tags: ['跳棋', '游戏']},
				{char: "⛁", name: "白跳棋王", ename: "White Draughts King", tags: ['跳棋', '游戏']},
				{char: "⛂", name: "黑跳棋", ename: "Black Draughts Man", tags: ['跳棋', '游戏']},
				{char: "⛃", name: "黑跳棋王", ename: "Black Draughts King", tags: ['跳棋', '游戏']},
				{char: "⛉", name: "翻转白将棋", ename: "Turned White Shogi Piece", tags: ['将棋', '游戏']},
				{char: "⛊", name: "翻转黑将棋", ename: "Turned Black Shogi Piece", tags: ['将棋', '游戏']},
				{char: "⛹", name: "持球人", ename: "Person with Ball", tags: ['人', '球']},
				{char: "⛳", name: "洞中旗", ename: "Flag In Hole", tags: ['旗', '洞']},

			]
		}
	]
};