const data = {
	name: "体育",
	groups: [
		{
			name: '围棋',
			symbols: [
				{char: "●", name: "黑子", ename: "BLACK CIRCLE", tags: ['黑棋']},
				{char: "○", name: "白子", ename: "WHITE CIRCLE", tags: ['白棋']},
				{char: "☆", name: "星位、天元", ename: "WHITE STAR", tags: []},
				{char: "⚆", name: "棋谱·有提子的白子", ename: "White Circle with Dot Right", tags: ['记谱', '白棋']},
				{char: "⚇", name: "棋谱·提多子的白子", ename: "White Circle with Two Dots", tags: ['记谱', '白棋', '块提']},
				{char: "⚈", name: "棋谱·有提子的黑子", ename: "Black Circle with White Dot Right", tags: ['记谱', '黑棋']},
				{
					char: "⚉", name: "棋谱·提多子的黑子", ename: "Black Circle with Two White Dots",
					tags: ['记谱', '黑棋', '块提']
				},
				{char: "⛣", name: "棋谱·提多子的白子", ename: "WHITE CIRCLE WITH DOT RIGHT", tags: ['记谱', '白棋', '块提']}
			]
		},
		{
			name: "国际象棋",
			symbols: [
				{char: "♔", name: "白国王", ename: "White Chess King", tags: []},
				{char: "♕", name: "白王后", ename: "White Chess Queen", tags: []},
				{char: "♖", name: "白战车", ename: "White Chess Rook", tags: []},
				{char: "♗", name: "白主教", ename: "White Chess Bishop", tags: []},
				{char: "♘", name: "白骑士", ename: "White Chess Knight", tags: []},
				{char: "♙", name: "白兵", ename: "White Chess Pawn", tags: []},
				{char: "♚", name: "黑国王", ename: "Black Chess King", tags: []},
				{char: "♛", name: "黑王后", ename: "Black Chess Queen", tags: []},
				{char: "♜", name: "黑战车", ename: "Black Chess Rook", tags: []},
				{char: "♝", name: "黑主教", ename: "Black Chess Bishop", tags: []},
				{char: "♞", name: "黑骑士", ename: "Black Chess Knight", tags: []},
				{char: "♟", name: "黑兵", ename: "Black Chess Pawn", tags: []},
				{char: "🨀", name: "中性国王", ename: "Neutral Chess King", tags: []},
				{char: "🨁", name: "中性王后", ename: "Neutral Chess Queen", tags: []},
				{char: "🨂", name: "中性战车", ename: "Neutral Chess Rook", tags: []},
				{char: "🨃", name: "中性主教", ename: "Neutral Chess Bishop", tags: []},
				{char: "🨄", name: "中性骑士", ename: "Neutral Chess Knight", tags: []},
				{char: "🨅", name: "中性兵", ename: "Neutral Chess Pawn", tags: []},

				{char: "🨉", name: "向右白国王", ename: "White Chess King Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨊", name: "向右白王后", ename: "White Chess Queen Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨋", name: "向右白战车", ename: "White Chess Rook Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨌", name: "向右白主教", ename: "White Chess Bishop Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨍", name: "向右白骑士", ename: "White Chess Knight Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨎", name: "向右白兵", ename: "White Chess Pawn Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨏", name: "向右黑国王", ename: "Black Chess King Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨐", name: "向右黑王后", ename: "Black Chess Queen Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨑", name: "向右黑战车", ename: "Black Chess Rook Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨒", name: "向右黑主教", ename: "Black Chess Bishop Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨓", name: "向右黑骑士", ename: "Black Chess Knight Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨔", name: "向右黑兵", ename: "Black Chess Pawn Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨕", name: "向右中性国王", ename: "Neutral Chess King Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨖", name: "向右中性王后", ename: "Neutral Chess Queen Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨗", name: "向右中性战车", ename: "Neutral Chess Rook Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨘", name: "向右中性主教", ename: "Neutral Chess Bishop Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨙", name: "向右中性骑士", ename: "Neutral Chess Knight Rotated Ninety Degrees", tags: ['90°']},
				{char: "🨚", name: "向右中性兵", ename: "Neutral Chess Pawn Rotated Ninety Degrees", tags: ['90°']},

				{char: "🨞", name: "倒白国王", ename: "White Chess Turned King", tags: ['镜像', '180°']},
				{char: "🨟", name: "倒白王后", ename: "White Chess Turned Queen", tags: ['镜像', '180°']},
				{char: "🨠", name: "倒白战车", ename: "White Chess Turned Rook", tags: ['镜像', '180°']},
				{char: "🨡", name: "倒白主教", ename: "White Chess Turned Bishop", tags: ['镜像', '180°']},
				{char: "🨢", name: "倒白骑士", ename: "White Chess Turned Knight", tags: ['镜像', '180°']},
				{char: "🨣", name: "倒白兵", ename: "White Chess Turned Pawn", tags: ['镜像', '180°']},
				{char: "🨤", name: "倒黑国王", ename: "Black Chess Turned King", tags: ['镜像', '180°']},
				{char: "🨥", name: "倒黑王后", ename: "Black Chess Turned Queen", tags: ['镜像', '180°']},
				{char: "🨦", name: "倒黑战车", ename: "Black Chess Turned Rook", tags: ['镜像', '180°']},
				{char: "🨧", name: "倒黑主教", ename: "Black Chess Turned Bishop", tags: ['镜像', '180°']},
				{char: "🨨", name: "倒黑骑士", ename: "Black Chess Turned Knight", tags: ['镜像', '180°']},
				{char: "🨩", name: "倒黑兵", ename: "Black Chess Turned Pawn", tags: ['镜像', '180°']},
				{char: "🨪", name: "倒中性国王", ename: "Neutral Chess Turned King", tags: ['镜像', '180°']},
				{char: "🨫", name: "倒中性王后", ename: "Neutral Chess Turned Queen", tags: ['镜像', '180°']},
				{char: "🨬", name: "倒中性战车", ename: "Neutral Chess Turned Rook", tags: ['镜像', '180°']},
				{char: "🨭", name: "倒中性主教", ename: "Neutral Chess Turned Bishop", tags: ['镜像', '180°']},
				{char: "🨮", name: "倒中性骑士", ename: "Neutral Chess Turned Knight", tags: ['镜像', '180°']},
				{char: "🨯", name: "倒中性兵", ename: "Neutral Chess Turned Pawn", tags: ['镜像', '180°']},

				{char: "🨳", name: "向左白国王", ename: "White Chess King Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{char: "🨴", name: "向左白王后", ename: "White Chess Queen Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{char: "🨵", name: "向左白战车", ename: "White Chess Rook Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{
					char: "🨶",
					name: "向左白主教",
					ename: "White Chess Bishop Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{
					char: "🨷",
					name: "向左白骑士",
					ename: "White Chess Knight Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{char: "🨸", name: "向左白兵", ename: "White Chess Pawn Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{char: "🨹", name: "向左黑国王", ename: "Black Chess King Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{char: "🨺", name: "向左黑王后", ename: "Black Chess Queen Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{char: "🨻", name: "向左黑战车", ename: "Black Chess Rook Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{
					char: "🨼",
					name: "向左黑主教",
					ename: "Black Chess Bishop Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{
					char: "🨽",
					name: "向左黑骑士",
					ename: "Black Chess Knight Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{char: "🨾", name: "向左黑兵", ename: "Black Chess Pawn Rotated Two Hundred Seventy Degrees", tags: ['270°']},
				{
					char: "🨿",
					name: "向左中性国王",
					ename: "Neutral Chess King Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{
					char: "🩀",
					name: "向左中性王后",
					ename: "Neutral Chess Queen Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{
					char: "🩁",
					name: "向左中性战车",
					ename: "Neutral Chess Rook Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{
					char: "🩂",
					name: "向左中性主教",
					ename: "Neutral Chess Bishop Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{
					char: "🩃",
					name: "向左中性骑士",
					ename: "Neutral Chess Knight Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},
				{
					char: "🩄",
					name: "向左中性兵",
					ename: "Neutral Chess Pawn Rotated Two Hundred Seventy Degrees",
					tags: ['270°']
				},

				{char: "🨆", name: "向右上白骑士", ename: "White Chess Knight Rotated Forty-Five Degrees", tags: ['45°']},
				{char: "🨇", name: "向右上黑骑士", ename: "Black Chess Knight Rotated Forty-Five Degrees", tags: ['45°']},
				{char: "🨈", name: "向右上中性骑士", ename: "Neutral Chess Knight Rotated Forty-Five Degrees", tags: ['45°']},
				{
					char: "🨛", name: "向右下白骑士", ename: "White Chess Knight Rotated One Hundred Thirty-Five Degrees",
					tags: ['135°']
				},
				{
					char: "🨜", name: "向右下黑骑士", ename: "Black Chess Knight Rotated One Hundred Thirty-Five Degrees",
					tags: ['135°']
				},
				{
					char: "🨝", name: "向右下中性骑士", ename: "Neutral Chess Knight Rotated One Hundred Thirty-Five Degrees",
					tags: ['135°']
				},
				{
					char: "🨰", name: "向左下白骑士", ename: "White Chess Knight Rotated Two Hundred Twenty-Five Degrees",
					tags: ['225°']
				},
				{
					char: "🨱", name: "向左下黑骑士", ename: "Black Chess Knight Rotated Two Hundred Twenty-Five Degrees",
					tags: ['225°']
				},
				{
					char: "🨲", name: "向左下中性骑士", ename: "Neutral Chess Knight Rotated Two Hundred Twenty-Five Degrees",
					tags: ['225°']
				},
				{
					char: "🩅", name: "向左上白骑士", ename: "White Chess Knight Rotated Three Hundred Fifteen Degrees",
					tags: ['315°']
				},
				{
					char: "🩆", name: "向左上黑骑士", ename: "Black Chess Knight Rotated Three Hundred Fifteen Degrees",
					tags: ['315°']
				},
				{
					char: "🩇", name: "向左上中性骑士", ename: "Neutral Chess Knight Rotated Three Hundred Fifteen Degrees",
					tags: ['315°']
				},

				{char: "🩈", name: "白等跳马", ename: "White Chess Equihopper", tags: []},
				{char: "🩉", name: "黑等跳马", ename: "Black Chess Equihopper", tags: []},
				{char: "🩊", name: "中性等跳马", ename: "Neutral Chess Equihopper", tags: []},
				{char: "🩋", name: "白等跳马旋转90°", ename: "White Chess Equihopper Rotated Ninety Degrees", tags: []},
				{char: "🩌", name: "黑等跳马旋转90°", ename: "Black Chess Equihopper Rotated Ninety Degrees", tags: []},
				{char: "🩍", name: "中性等跳马旋转90°", ename: "Neutral Chess Equihopper Rotated Ninety Degrees", tags: []},
				{char: "🩎", name: "白骑士王后", ename: "White Chess Knight-Queen", tags: []},
				{char: "🩏", name: "白骑士战车", ename: "White Chess Knight-Rook", tags: []},
				{char: "🩐", name: "白骑士主教", ename: "White Chess Knight-Bishop", tags: []},
				{char: "🩑", name: "黑骑士王后", ename: "Black Chess Knight-Queen", tags: []},
				{char: "🩒", name: "黑骑士战车", ename: "Black Chess Knight-Rook", tags: []},
				{char: "🩓", name: "黑骑士主教", ename: "Black Chess Knight-Bishop", tags: []}
			]
		},
		{
			name: "中国象棋",
			symbols: [
				{char: "🩠", name: "红帅", ename: "Xiangqi Red General", tags: []},
				{char: "🩡", name: "红仕", ename: "Xiangqi Red Mandarin", tags: []},
				{char: "🩢", name: "红相", ename: "Xiangqi Red Elephant", tags: []},
				{char: "🩣", name: "红马", ename: "Xiangqi Red Horse", tags: []},
				{char: "🩤", name: "红车", ename: "Xiangqi Red Chariot", tags: []},
				{char: "🩥", name: "红炮", ename: "Xiangqi Red Cannon", tags: []},
				{char: "🩦", name: "红兵", ename: "Xiangqi Red Soldier", tags: []},
				{char: "🩧", name: "黑将", ename: "Xiangqi Black General", tags: []},
				{char: "🩨", name: "黑士", ename: "Xiangqi Black Mandarin", tags: []},
				{char: "🩩", name: "黑象", ename: "Xiangqi Black Elephant", tags: []},
				{char: "🩪", name: "黑马", ename: "Xiangqi Black Horse", tags: []},
				{char: "🩫", name: "黑车", ename: "Xiangqi Black Chariot", tags: []},
				{char: "🩬", name: "黑炮", ename: "Xiangqi Black Cannon", tags: []},
				{char: "🩭", name: "黑卒", ename: "Xiangqi Black Soldier", tags: []}
			]
		},
		{
			name: "扑克牌",
			symbols: [
				{char: "🂡", name: "黑桃A", ename: "Playing Card Ace of Spades"},
				{char: "🂢", name: "黑桃2", ename: "Playing Card Two of Spades"},
				{char: "🂣", name: "黑桃3", ename: "Playing Card Three of Spades"},
				{char: "🂤", name: "黑桃4", ename: "Playing Card Four of Spades"},
				{char: "🂥", name: "黑桃5", ename: "Playing Card Five of Spades"},
				{char: "🂦", name: "黑桃6", ename: "Playing Card Six of Spades"},
				{char: "🂧", name: "黑桃7", ename: "Playing Card Seven of Spades"},
				{char: "🂨", name: "黑桃8", ename: "Playing Card Eight of Spades"},
				{char: "🂩", name: "黑桃9", ename: "Playing Card Nine of Spades"},
				{char: "🂪", name: "黑桃10", ename: "Playing Card Ten of Spades"},
				{char: "🂫", name: "黑桃J", ename: "Playing Card Jack of Spades"},
				{char: "🂭", name: "黑桃Q", ename: "Playing Card Queen of Spades"},
				{char: "🂮", name: "黑桃K", ename: "Playing Card King of Spades"},
				{char: "🂬", name: "黑桃骑士", ename: "Playing Card Knight of Spades"},

				{char: "🂱", name: "红心A/红桃A", ename: "Playing Card Ace of Hearts"},
				{char: "🂲", name: "红心2/红桃2", ename: "Playing Card Two of Hearts"},
				{char: "🂳", name: "红心3/红桃3", ename: "Playing Card Three of Hearts"},
				{char: "🂴", name: "红心4/红桃4", ename: "Playing Card Four of Hearts"},
				{char: "🂵", name: "红心5/红桃5", ename: "Playing Card Five of Hearts"},
				{char: "🂶", name: "红心6/红桃6", ename: "Playing Card Six of Hearts"},
				{char: "🂷", name: "红心7/红桃7", ename: "Playing Card Seven of Hearts"},
				{char: "🂸", name: "红心8/红桃8", ename: "Playing Card Eight of Hearts"},
				{char: "🂹", name: "红心9/红桃9", ename: "Playing Card Nine of Hearts"},
				{char: "🂺", name: "红心10/红桃10", ename: "Playing Card Ten of Hearts"},
				{char: "🂻", name: "红心J/红桃J", ename: "Playing Card Jack of Hearts"},
				{char: "🂽", name: "红心Q/红桃Q", ename: "Playing Card Queen of Hearts"},
				{char: "🂾", name: "红心K/红桃K", ename: "Playing Card King of Hearts"},
				{char: "🂼", name: "红心骑士/红桃骑士", ename: "Playing Card Knight of Hearts"},

				{char: "🃑", name: "梅花A/草花A", ename: "Playing Card Ace of Clubs"},
				{char: "🃒", name: "梅花2/草花2", ename: "Playing Card Two of Clubs"},
				{char: "🃓", name: "梅花3/草花3", ename: "Playing Card Three of Clubs"},
				{char: "🃔", name: "梅花4/草花4", ename: "Playing Card Four of Clubs"},
				{char: "🃕", name: "梅花5/草花5", ename: "Playing Card Five of Clubs"},
				{char: "🃖", name: "梅花6/草花6", ename: "Playing Card Six of Clubs"},
				{char: "🃗", name: "梅花7/草花7", ename: "Playing Card Seven of Clubs"},
				{char: "🃘", name: "梅花8/草花8", ename: "Playing Card Eight of Clubs"},
				{char: "🃙", name: "梅花9/草花9", ename: "Playing Card Nine of Clubs"},
				{char: "🃚", name: "梅花10/草花10", ename: "Playing Card Ten of Clubs"},
				{char: "🃛", name: "梅花J/草花J", ename: "Playing Card Jack of Clubs"},
				{char: "🃝", name: "梅花Q/草花Q", ename: "Playing Card Queen of Clubs"},
				{char: "🃞", name: "梅花K/草花K", ename: "Playing Card King of Clubs"},
				{char: "🃜", name: "梅花骑士/草花骑士", ename: "Playing Card Knight of Clubs"},

				{char: "🃁", name: "方块A/方片A", ename: "Playing Card Ace of Diamonds"},
				{char: "🃂", name: "方块2/方片2", ename: "Playing Card Two of Diamonds"},
				{char: "🃃", name: "方块3/方片3", ename: "Playing Card Three of Diamonds"},
				{char: "🃄", name: "方块4/方片4", ename: "Playing Card Four of Diamonds"},
				{char: "🃅", name: "方块5/方片5", ename: "Playing Card Five of Diamonds"},
				{char: "🃆", name: "方块6/方片6", ename: "Playing Card Six of Diamonds"},
				{char: "🃇", name: "方块7/方片7", ename: "Playing Card Seven of Diamonds"},
				{char: "🃈", name: "方块8/方片8", ename: "Playing Card Eight of Diamonds"},
				{char: "🃉", name: "方块9/方片9", ename: "Playing Card Nine of Diamonds"},
				{char: "🃊", name: "方块10/方片10", ename: "Playing Card Ten of Diamonds"},
				{char: "🃋", name: "方块J/方片J", ename: "Playing Card Jack of Diamonds"},
				{char: "🃍", name: "方块Q/方片Q", ename: "Playing Card Queen of Diamonds"},
				{char: "🃎", name: "方块K/方片K", ename: "Playing Card King of Diamonds"},
				{char: "🃌", name: "方块骑士/方片骑士", ename: "Playing Card Knight of Diamonds"},

				{char: "🃏", name: "黑小丑/大王/大鬼", ename: "Playing Card Black Joker", tags: ['百搭', '鬼牌', '王牌']},
				{char: "🃟", name: "白小丑/小王/小鬼", ename: "Playing Card White Joker", tags: ['百搭', '鬼牌', '王牌']},
				{
					char: "🂿", name: "红小丑/骑士/第三王", ename: "Playing Card Red Joker(used as the third joker)",
					tags: ['百搭', '鬼牌', '王牌']
				},

				{char: "♠", name: "黑桃", ename: "Black Spade Suit"},
				{char: "♡", name: "红心", ename: "White Heart Suit"},
				{char: "♢", name: "方块", ename: "White Diamond Suit"},
				{char: "♣", name: "梅花", ename: "Black Club Suit"},
				{char: "♤", name: "反色黑桃", ename: "White Spade Suit"},
				{char: "♥", name: "反色红心", ename: "Red Heart Suit"},
				{char: "♧", name: "反色梅花", ename: "White Club Suit"},
				{char: "♦", name: "反色方块", ename: "Red Diamond Suit"},

				{char: '🂠', name: "牌背", ename: "PLAYING CARD FOOL"},

				{char: "🃠", name: "傻瓜", ename: "PLAYING CARD FOOL"},
				{char: "🃡", name: "个人", ename: "PLAYING CARD TRUMP-01 individual"},
				{char: "🃵", name: "集体", ename: "Playing Card Back 21 collective"},
				{char: "🃢", name: "童年", ename: "PLAYING CARD TRUMP-02 childhood"},
				{char: "🃣", name: "少年", ename: "PLAYING CARD TRUMP-03 youth"},
				{char: "🃤", name: "成年", ename: "PLAYING CARD TRUMP-04 maturity"},
				{char: "🃥", name: "老年", ename: "PLAYING CARD TRUMP-05 old age"},
				{char: "🃦", name: "早上", ename: "PLAYING CARD TRUMP-06 morning"},
				{char: "🃧", name: "下午", ename: "PLAYING CARD TRUMP-07 afternoon"},
				{char: "🃨", name: "晚上", ename: "PLAYING CARD TRUMP-08 evening"},
				{char: "🃩", name: "夜晚", ename: "PLAYING CARD TRUMP-09 night"},
				{char: "🃪", name: "土风（四元素之二）", ename: "PLAYING CARD TRUMP-10 earth and air"},
				{char: "🃫", name: "水火（四元素之二）", ename: "PLAYING CARD TRUMP-11 water and fire"},
				{char: "🃬", name: "跳舞", ename: "PLAYING CARD TRUMP-12 dance"},
				{char: "🃭", name: "购物", ename: "PLAYING CARD TRUMP-13 shopping"},
				{char: "🃮", name: "户外", ename: "PLAYING CARD TRUMP-14 open air"},
				{char: "🃯", name: "视觉艺术", ename: "PLAYING CARD TRUMP-15 visual arts"},
				{char: "🃰", name: "春", ename: "PLAYING CARD TRUMP-16 spring"},
				{char: "🃱", name: "夏", ename: "PLAYING CARD TRUMP-17 summer"},
				{char: "🃲", name: "秋", ename: "PLAYING CARD TRUMP-18 autumn"},
				{char: "🃳", name: "冬", ename: "PLAYING CARD TRUMP-19 winter"},
				{char: "🃴", name: "牌局", ename: "Playing Card Back 20 the game"}
			]
		},
		{
			name: "麻将",
			symbols: [
				{char: "🀀", name: "东风", ename: "Mahjong Tile East Wind", tags: []},
				{char: "🀁", name: "南风", ename: "Mahjong Tile South Wind", tags: []},
				{char: "🀂", name: "西风", ename: "Mahjong Tile West Wind", tags: []},
				{char: "🀃", name: "北风", ename: "Mahjong Tile North Wind", tags: []},
				{char: "🀄", name: "红中", ename: "Mahjong Tile Red Dragon", tags: []},
				{char: "🀅", name: "发财", ename: "Mahjong Tile Green Dragon", tags: []},
				{char: "🀆", name: "白板", ename: "Mahjong Tile White Dragon", tags: []},
				{char: "🀇", name: "一万", ename: "Mahjong Tile One of Characters", tags: []},
				{char: "🀈", name: "二万", ename: "Mahjong Tile Two of Characters", tags: []},
				{char: "🀉", name: "三万", ename: "Mahjong Tile Three of Characters", tags: []},
				{char: "🀊", name: "四万", ename: "Mahjong Tile Four of Characters", tags: []},
				{char: "🀋", name: "五万", ename: "Mahjong Tile Five of Characters", tags: []},
				{char: "🀌", name: "六万", ename: "Mahjong Tile Six of Characters", tags: []},
				{char: "🀍", name: "七万", ename: "Mahjong Tile Seven of Characters", tags: []},
				{char: "🀎", name: "八万", ename: "Mahjong Tile Eight of Characters", tags: []},
				{char: "🀏", name: "九万", ename: "Mahjong Tile Nine of Characters", tags: []},
				{char: "🀐", name: "一索", ename: "Mahjong Tile One of Bamboos", tags: ['一条', '麻雀']},
				{char: "🀑", name: "二索", ename: "Mahjong Tile Two of Bamboos", tags: ['二条']},
				{char: "🀒", name: "三索", ename: "Mahjong Tile Three of Bamboos", tags: ['三条']},
				{char: "🀓", name: "四索", ename: "Mahjong Tile Four of Bamboos", tags: ['四条']},
				{char: "🀔", name: "五索", ename: "Mahjong Tile Five of Bamboos", tags: ['五条']},
				{char: "🀕", name: "六索", ename: "Mahjong Tile Six of Bamboos", tags: ['六条']},
				{char: "🀖", name: "七索", ename: "Mahjong Tile Seven of Bamboos", tags: ['七条']},
				{char: "🀗", name: "八索", ename: "Mahjong Tile Eight of Bamboos", tags: ['八条']},
				{char: "🀘", name: "九索", ename: "Mahjong Tile Nine of Bamboos", tags: ['九条']},
				{char: "🀙", name: "一筒", ename: "Mahjong Tile One of Circles", tags: ['一饼']},
				{char: "🀚", name: "二筒", ename: "Mahjong Tile Two of Circles", tags: ['二饼']},
				{char: "🀛", name: "三筒", ename: "Mahjong Tile Three of Circles", tags: ['三饼']},
				{char: "🀜", name: "四筒", ename: "Mahjong Tile Four of Circles", tags: ['四饼']},
				{char: "🀝", name: "五筒", ename: "Mahjong Tile Five of Circles", tags: ['五饼']},
				{char: "🀞", name: "六筒", ename: "Mahjong Tile Six of Circles", tags: ['六饼']},
				{char: "🀟", name: "七筒", ename: "Mahjong Tile Seven of Circles", tags: ['七饼']},
				{char: "🀠", name: "八筒", ename: "Mahjong Tile Eight of Circles", tags: ['八饼']},
				{char: "🀡", name: "九筒", ename: "Mahjong Tile Nine of Circles", tags: ['九饼']},
				{char: "🀦", name: "梅", ename: "Mahjong Tile Plum", tags: []},
				{char: "🀧", name: "兰", ename: "Mahjong Tile Orchid", tags: []},
				{char: "🀨", name: "竹", ename: "Mahjong Tile Bamboo", tags: []},
				{char: "🀩", name: "菊", ename: "Mahjong Tile Chrysanthemum", tags: []},
				{char: "🀢", name: "春", ename: "Mahjong Tile Spring", tags: []},
				{char: "🀣", name: "夏", ename: "Mahjong Tile Summer", tags: []},
				{char: "🀤", name: "秋", ename: "Mahjong Tile Autumn", tags: []},
				{char: "🀥", name: "冬", ename: "Mahjong Tile Winter", tags: []},
				{char: "🀪", name: "百搭", ename: "Mahjong Tile Joker", tags: []},
				{char: "🀫", name: "背面", ename: "Mahjong Tile Back", tags: []}
			]
		},
		{
			name: "骰子/色子",
			symbols: [
				{char: "⚀", name: "1点", ename: "Die Face-1"},
				{char: "⚁", name: "2点", ename: "Die Face-2"},
				{char: "⚂", name: "3点", ename: "Die Face-3"},
				{char: "⚃", name: "4点", ename: "Die Face-4"},
				{char: "⚄", name: "5点", ename: "Die Face-5"},
				{char: "⚅", name: "6点", ename: "Die Face-6"}
			]
		},
		{
			name: "多米诺骨牌",
			symbols: [
				{char: '🀰', name: '水平骨牌背面', ename: 'DOMINO TILE HORIZONTAL BACK'},
				{char: '🀱', name: '水平骨牌 0-0', ename: 'DOMINO TILE HORIZONTAL-00-00'},
				{char: '🀲', name: '水平骨牌 0-1', ename: 'DOMINO TILE HORIZONTAL-00-01'},
				{char: '🀳', name: '水平骨牌 0-2', ename: 'DOMINO TILE HORIZONTAL-00-02'},
				{char: '🀴', name: '水平骨牌 0-3', ename: 'DOMINO TILE HORIZONTAL-00-03'},
				{char: '🀵', name: '水平骨牌 0-4', ename: 'DOMINO TILE HORIZONTAL-00-04'},
				{char: '🀶', name: '水平骨牌 0-5', ename: 'DOMINO TILE HORIZONTAL-00-05'},
				{char: '🀷', name: '水平骨牌 0-6', ename: 'DOMINO TILE HORIZONTAL-00-06'},
				{char: '🀸', name: '水平骨牌 1-0', ename: 'DOMINO TILE HORIZONTAL-01-00'},
				{char: '🀹', name: '水平骨牌 1-1', ename: 'DOMINO TILE HORIZONTAL-01-01'},
				{char: '🀺', name: '水平骨牌 1-2', ename: 'DOMINO TILE HORIZONTAL-01-02'},
				{char: '🀻', name: '水平骨牌 1-3', ename: 'DOMINO TILE HORIZONTAL-01-03'},
				{char: '🀼', name: '水平骨牌 1-4', ename: 'DOMINO TILE HORIZONTAL-01-04'},
				{char: '🀽', name: '水平骨牌 1-5', ename: 'DOMINO TILE HORIZONTAL-01-05'},
				{char: '🀾', name: '水平骨牌 1-6', ename: 'DOMINO TILE HORIZONTAL-01-06'},
				{char: '🀿', name: '水平骨牌 2-0', ename: 'DOMINO TILE HORIZONTAL-02-00'},
				{char: '🁀', name: '水平骨牌 2-1', ename: 'DOMINO TILE HORIZONTAL-02-01'},
				{char: '🁁', name: '水平骨牌 2-2', ename: 'DOMINO TILE HORIZONTAL-02-02'},
				{char: '🁂', name: '水平骨牌 2-3', ename: 'DOMINO TILE HORIZONTAL-02-03'},
				{char: '🁃', name: '水平骨牌 2-4', ename: 'DOMINO TILE HORIZONTAL-02-04'},
				{char: '🁄', name: '水平骨牌 2-5', ename: 'DOMINO TILE HORIZONTAL-02-05'},
				{char: '🁅', name: '水平骨牌 2-6', ename: 'DOMINO TILE HORIZONTAL-02-06'},
				{char: '🁆', name: '水平骨牌 3-0', ename: 'DOMINO TILE HORIZONTAL-03-00'},
				{char: '🁇', name: '水平骨牌 3-1', ename: 'DOMINO TILE HORIZONTAL-03-01'},
				{char: '🁈', name: '水平骨牌 3-2', ename: 'DOMINO TILE HORIZONTAL-03-02'},
				{char: '🁉', name: '水平骨牌 3-3', ename: 'DOMINO TILE HORIZONTAL-03-03'},
				{char: '🁊', name: '水平骨牌 3-4', ename: 'DOMINO TILE HORIZONTAL-03-04'},
				{char: '🁋', name: '水平骨牌 3-5', ename: 'DOMINO TILE HORIZONTAL-03-05'},
				{char: '🁌', name: '水平骨牌 3-6', ename: 'DOMINO TILE HORIZONTAL-03-06'},
				{char: '🁍', name: '水平骨牌 4-0', ename: 'DOMINO TILE HORIZONTAL-04-00'},
				{char: '🁎', name: '水平骨牌 4-1', ename: 'DOMINO TILE HORIZONTAL-04-01'},
				{char: '🁏', name: '水平骨牌 4-2', ename: 'DOMINO TILE HORIZONTAL-04-02'},
				{char: '🁐', name: '水平骨牌 4-3', ename: 'DOMINO TILE HORIZONTAL-04-03'},
				{char: '🁑', name: '水平骨牌 4-4', ename: 'DOMINO TILE HORIZONTAL-04-04'},
				{char: '🁒', name: '水平骨牌 4-5', ename: 'DOMINO TILE HORIZONTAL-04-05'},
				{char: '🁓', name: '水平骨牌 4-6', ename: 'DOMINO TILE HORIZONTAL-04-06'},
				{char: '🁔', name: '水平骨牌 5-0', ename: 'DOMINO TILE HORIZONTAL-05-00'},
				{char: '🁕', name: '水平骨牌 5-1', ename: 'DOMINO TILE HORIZONTAL-05-01'},
				{char: '🁖', name: '水平骨牌 5-2', ename: 'DOMINO TILE HORIZONTAL-05-02'},
				{char: '🁗', name: '水平骨牌 5-3', ename: 'DOMINO TILE HORIZONTAL-05-03'},
				{char: '🁘', name: '水平骨牌 5-4', ename: 'DOMINO TILE HORIZONTAL-05-04'},
				{char: '🁙', name: '水平骨牌 5-5', ename: 'DOMINO TILE HORIZONTAL-05-05'},
				{char: '🁚', name: '水平骨牌 5-6', ename: 'DOMINO TILE HORIZONTAL-05-06'},
				{char: '🁛', name: '水平骨牌 6-0', ename: 'DOMINO TILE HORIZONTAL-06-00'},
				{char: '🁜', name: '水平骨牌 6-1', ename: 'DOMINO TILE HORIZONTAL-06-01'},
				{char: '🁝', name: '水平骨牌 6-2', ename: 'DOMINO TILE HORIZONTAL-06-02'},
				{char: '🁞', name: '水平骨牌 6-3', ename: 'DOMINO TILE HORIZONTAL-06-03'},
				{char: '🁟', name: '水平骨牌 6-4', ename: 'DOMINO TILE HORIZONTAL-06-04'},
				{char: '🁠', name: '水平骨牌 6-5', ename: 'DOMINO TILE HORIZONTAL-06-05'},
				{char: '🁡', name: '水平骨牌 6-6', ename: 'DOMINO TILE HORIZONTAL-06-06'},
				{char: '🁢', name: '垂直骨牌背面', ename: 'DOMINO TILE VERTICAL BACK'},
				{char: '🁣', name: '垂直骨牌 0-0', ename: 'DOMINO TILE VERTICAL-00-00'},
				{char: '🁤', name: '垂直骨牌 0-1', ename: 'DOMINO TILE VERTICAL-00-01'},
				{char: '🁥', name: '垂直骨牌 0-2', ename: 'DOMINO TILE VERTICAL-00-02'},
				{char: '🁦', name: '垂直骨牌 0-3', ename: 'DOMINO TILE VERTICAL-00-03'},
				{char: '🁧', name: '垂直骨牌 0-4', ename: 'DOMINO TILE VERTICAL-00-04'},
				{char: '🁨', name: '垂直骨牌 0-5', ename: 'DOMINO TILE VERTICAL-00-05'},
				{char: '🁩', name: '垂直骨牌 0-6', ename: 'DOMINO TILE VERTICAL-00-06'},
				{char: '🁪', name: '垂直骨牌 1-0', ename: 'DOMINO TILE VERTICAL-01-00'},
				{char: '🁫', name: '垂直骨牌 1-1', ename: 'DOMINO TILE VERTICAL-01-01'},
				{char: '🁬', name: '垂直骨牌 1-2', ename: 'DOMINO TILE VERTICAL-01-02'},
				{char: '🁭', name: '垂直骨牌 1-3', ename: 'DOMINO TILE VERTICAL-01-03'},
				{char: '🁮', name: '垂直骨牌 1-4', ename: 'DOMINO TILE VERTICAL-01-04'},
				{char: '🁯', name: '垂直骨牌 1-5', ename: 'DOMINO TILE VERTICAL-01-05'},
				{char: '🁰', name: '垂直骨牌 1-6', ename: 'DOMINO TILE VERTICAL-01-06'},
				{char: '🁱', name: '垂直骨牌 2-0', ename: 'DOMINO TILE VERTICAL-02-00'},
				{char: '🁲', name: '垂直骨牌 2-1', ename: 'DOMINO TILE VERTICAL-02-01'},
				{char: '🁳', name: '垂直骨牌 2-2', ename: 'DOMINO TILE VERTICAL-02-02'},
				{char: '🁴', name: '垂直骨牌 2-3', ename: 'DOMINO TILE VERTICAL-02-03'},
				{char: '🁵', name: '垂直骨牌 2-4', ename: 'DOMINO TILE VERTICAL-02-04'},
				{char: '🁶', name: '垂直骨牌 2-5', ename: 'DOMINO TILE VERTICAL-02-05'},
				{char: '🁷', name: '垂直骨牌 2-6', ename: 'DOMINO TILE VERTICAL-02-06'},
				{char: '🁸', name: '垂直骨牌 3-0', ename: 'DOMINO TILE VERTICAL-03-00'},
				{char: '🁹', name: '垂直骨牌 3-1', ename: 'DOMINO TILE VERTICAL-03-01'},
				{char: '🁺', name: '垂直骨牌 3-2', ename: 'DOMINO TILE VERTICAL-03-02'},
				{char: '🁻', name: '垂直骨牌 3-3', ename: 'DOMINO TILE VERTICAL-03-03'},
				{char: '🁼', name: '垂直骨牌 3-4', ename: 'DOMINO TILE VERTICAL-03-04'},
				{char: '🁽', name: '垂直骨牌 3-5', ename: 'DOMINO TILE VERTICAL-03-05'},
				{char: '🁾', name: '垂直骨牌 3-6', ename: 'DOMINO TILE VERTICAL-03-06'},
				{char: '🁿', name: '垂直骨牌 4-0', ename: 'DOMINO TILE VERTICAL-04-00'},
				{char: '🂀', name: '垂直骨牌 4-1', ename: 'DOMINO TILE VERTICAL-04-01'},
				{char: '🂁', name: '垂直骨牌 4-2', ename: 'DOMINO TILE VERTICAL-04-02'},
				{char: '🂂', name: '垂直骨牌 4-3', ename: 'DOMINO TILE VERTICAL-04-03'},
				{char: '🂃', name: '垂直骨牌 4-4', ename: 'DOMINO TILE VERTICAL-04-04'},
				{char: '🂄', name: '垂直骨牌 4-5', ename: 'DOMINO TILE VERTICAL-04-05'},
				{char: '🂅', name: '垂直骨牌 4-6', ename: 'DOMINO TILE VERTICAL-04-06'},
				{char: '🂆', name: '垂直骨牌 5-0', ename: 'DOMINO TILE VERTICAL-05-00'},
				{char: '🂇', name: '垂直骨牌 5-1', ename: 'DOMINO TILE VERTICAL-05-01'},
				{char: '🂈', name: '垂直骨牌 5-2', ename: 'DOMINO TILE VERTICAL-05-02'},
				{char: '🂉', name: '垂直骨牌 5-3', ename: 'DOMINO TILE VERTICAL-05-03'},
				{char: '🂊', name: '垂直骨牌 5-4', ename: 'DOMINO TILE VERTICAL-05-04'},
				{char: '🂋', name: '垂直骨牌 5-5', ename: 'DOMINO TILE VERTICAL-05-05'},
				{char: '🂌', name: '垂直骨牌 5-6', ename: 'DOMINO TILE VERTICAL-05-06'},
				{char: '🂍', name: '垂直骨牌 6-0', ename: 'DOMINO TILE VERTICAL-06-00'},
				{char: '🂎', name: '垂直骨牌 6-1', ename: 'DOMINO TILE VERTICAL-06-01'},
				{char: '🂏', name: '垂直骨牌 6-2', ename: 'DOMINO TILE VERTICAL-06-02'},
				{char: '🂐', name: '垂直骨牌 6-3', ename: 'DOMINO TILE VERTICAL-06-03'},
				{char: '🂑', name: '垂直骨牌 6-4', ename: 'DOMINO TILE VERTICAL-06-04'},
				{char: '🂒', name: '垂直骨牌 6-5', ename: 'DOMINO TILE VERTICAL-06-05'},
				{char: '🂓', name: '垂直骨牌 6-6', ename: 'DOMINO TILE VERTICAL-06-06'}
			]
		},
		{
			name: '其他',
			symbols: [
				{char: "⚽", name: "足球", ename: "Soccer Ball", tags: ['足球', '运动']},
				{char: "⚾", name: "棒球", ename: "Baseball", tags: ['棒球', '运动']},
				{char: "🏀", name: "篮球", ename: "Basketball"},
				{char: "🏐", name: "排球", ename: "Volleyball"},
				{char: "🏈", name: "橄榄球", ename: "American Football"},
				{char: "🏉", name: "英式橄榄球", ename: "Rugby Football"},
				{char: "🎾", name: "网球", ename: "Tennis"},
				{char: "🎳", name: "保龄球", ename: "Bowling"},
				{char: "🏏", name: "板球", ename: "Cricket Game"},
				{char: "🏑", name: "曲棍球", ename: "Field Hockey"},
				{char: "🏒", name: "冰球", ename: "Ice Hockey"},
				{char: "🏓", name: "乒乓球", ename: "Ping Pong"},
				{char: "🏸", name: "羽毛球", ename: "Badminton"},
				{char: "🥊", name: "拳击手套", ename: "Boxing Glove"},
				{char: "🥋", name: "武术服", ename: "Martial Arts Uniform"},
				{char: "🥅", name: "球门", ename: "Goal Net"},
				{char: "🥇", name: "金牌", ename: "1st Place Medal"},
				{char: "🥈", name: "银牌", ename: "2nd Place Medal"},
				{char: "🥉", name: "铜牌", ename: "3rd Place Medal"},
				{char: "🏆", name: "奖杯", ename: "Trophy"},
				{char: "🎯", name: "靶心", ename: "Direct Hit", tags: ['射箭', '射击']},
				{char: "⛵", name: "帆船", ename: "Sailboat", tags: []},
				{char: "⛀", name: "白跳棋", ename: "White Draughts Man", tags: []},
				{char: "⛁", name: "白跳棋王", ename: "White Draughts King", tags: []},
				{char: "⛂", name: "黑跳棋", ename: "Black Draughts Man", tags: []},
				{char: "⛃", name: "黑跳棋王", ename: "Black Draughts King", tags: ['跳棋']},
				{char: "⛉", name: "翻转白将棋", ename: "Turned White Shogi Piece", tags: []},
				{char: "⛊", name: "翻转黑将棋", ename: "Turned Black Shogi Piece", tags: []},
				{char: "⛳", name: "洞中旗", ename: "Flag In Hole", tags: ['高尔夫球']},
				{char: "⛺", name: "帐篷", ename: "Tent", tags: ['露营', '户外']},
				{char: "⚔", name: "击剑", ename: "CROSSED SWORDS", tags: []},
				{char: "⛷", name: "滑雪者", ename: "SKIER", tags: ["运动", "人物"]},
				{char: "⛸", name: "冰鞋", ename: "ICE SKATE", tags: ["运动", "器材"]},
				{char: "⛹", name: "玩球的人", ename: "PERSON WITH BALL", tags: ["运动", "人物"]}
			]
		}
	]
};