const data = {
	name: '哲学、宗教、神秘学',
	groups: [
		{
			name: '《易经》符号（八卦、六十四卦）',
			symbols: [
				{char: "☯", name: "太极·阴阳两仪", ename: "Yin Yang", tags: ['易经', '道教']},
				{char: "⚊", name: "阳爻", ename: "MONOGRAM FOR YANG", tags: ['两仪', '阴阳', '四象', '八卦', '易经', '道教']},
				{char: "⚋", name: "阴爻", ename: "MONOGRAM FOR YIN", tags: ['两仪', '阴阳', '四象', '八卦', '易经', '道教']},
				{char: "⚌", name: "四象·太阳", ename: "MONOGRAM FOR GREATER YANG", tags: ['四象', '八卦', '易经', '道教']},
				{char: "⚍", name: "四象·少阴", ename: "MONOGRAM FOR LESSER YIN", tags: ['四象', '八卦', '易经', '道教']},
				{char: "⚎", name: "四象·少阳", ename: "MONOGRAM FOR LESSER YANG", tags: ['四象', '八卦', '易经', '道教']},
				{char: "⚏", name: "四象·太阴", ename: "MONOGRAM FOR GREATER YIN", tags: ['四象', '八卦', '易经', '道教']},

				{char: "☰", name: "八卦·乾（天）", ename: "Qian (Heaven)", tags: ['易经', '道教']},
				{char: "☱", name: "八卦·兑（沼泽）", ename: "Dui (Lake)", tags: ['易经', '道教']},
				{char: "☲", name: "八卦·离（火）", ename: "Li (Fire)", tags: ['易经', '道教']},
				{char: "☳", name: "八卦·震（雷）", ename: "Zhen (Thunder)", tags: ['易经', '道教']},
				{char: "☴", name: "八卦·巽（风）", ename: "Xun (Wind)", tags: ['易经', '道教']},
				{char: "☵", name: "八卦·坎（水）", ename: "Kan (Water)", tags: ['易经', '道教']},
				{char: "☶", name: "八卦·艮（山）", ename: "Gen (Mountain)", tags: ['易经', '道教']},
				{char: "☷", name: "八卦·坤（地）", ename: "Kun (Earth)", tags: ['易经', '道教']},

				{char: "䷀", name: "六十四卦·乾卦", ename: "Qian Hexagram", tags: ['易经', '道教']},
				{char: "䷁", name: "六十四卦·坤卦", ename: "Kun Hexagram", tags: ['易经', '道教']},
				{char: "䷂", name: "六十四卦·屯卦", ename: "Chun Hexagram", tags: ['易经', '道教']},
				{char: "䷃", name: "六十四卦·蒙卦", ename: "Meng Hexagram", tags: ['易经', '道教']},
				{char: "䷄", name: "六十四卦·需卦", ename: "Xu Hexagram", tags: ['易经', '道教']},
				{char: "䷅", name: "六十四卦·讼卦", ename: "Song Hexagram", tags: ['易经', '道教']},
				{char: "䷆", name: "六十四卦·师卦", ename: "Shi Hexagram", tags: ['易经', '道教']},
				{char: "䷇", name: "六十四卦·比卦", ename: "Bi Hexagram", tags: ['易经', '道教']},
				{char: "䷈", name: "六十四卦·小畜卦", ename: "Xiao Chu Hexagram", tags: ['易经', '道教']},
				{char: "䷉", name: "六十四卦·履卦", ename: "Lu Hexagram", tags: ['易经', '道教']},
				{char: "䷊", name: "六十四卦·泰卦", ename: "Tai Hexagram", tags: ['易经', '道教']},
				{char: "䷋", name: "六十四卦·否卦", ename: "Pi Hexagram", tags: ['易经', '道教']},
				{char: "䷌", name: "六十四卦·同人卦", ename: "Tong Ren Hexagram", tags: ['易经', '道教']},
				{char: "䷍", name: "六十四卦·大有卦", ename: "Da You Hexagram", tags: ['易经', '道教']},
				{char: "䷎", name: "六十四卦·谦卦", ename: "Qian Hexagram", tags: ['易经', '道教']},
				{char: "䷏", name: "六十四卦·豫卦", ename: "Yu Hexagram", tags: ['易经', '道教']},
				{char: "䷐", name: "六十四卦·随卦", ename: "Sui Hexagram", tags: ['易经', '道教']},
				{char: "䷑", name: "六十四卦·蛊卦", ename: "Gu Hexagram", tags: ['易经', '道教']},
				{char: "䷒", name: "六十四卦·临卦", ename: "Lin Hexagram", tags: ['易经', '道教']},
				{char: "䷓", name: "六十四卦·观卦", ename: "Guan Hexagram", tags: ['易经', '道教']},
				{char: "䷔", name: "六十四卦·噬嗑卦", ename: "Shi He Hexagram", tags: ['易经', '道教']},
				{char: "䷕", name: "六十四卦·贲卦", ename: "Bi Hexagram", tags: ['易经', '道教']},
				{char: "䷖", name: "六十四卦·剥卦", ename: "Bo Hexagram", tags: ['易经', '道教']},
				{char: "䷗", name: "六十四卦·复卦", ename: "Fu Hexagram", tags: ['易经', '道教']},
				{char: "䷘", name: "六十四卦·无妄卦", ename: "Wu Wang Hexagram", tags: ['易经', '道教']},
				{char: "䷙", name: "六十四卦·大畜卦", ename: "Da Chu Hexagram", tags: ['易经', '道教']},
				{char: "䷚", name: "六十四卦·颐卦", ename: "Yi Hexagram", tags: ['易经', '道教']},
				{char: "䷛", name: "六十四卦·大过卦", ename: "Da Guo Hexagram", tags: ['易经', '道教']},
				{char: "䷜", name: "六十四卦·坎卦", ename: "Kan Hexagram", tags: ['易经', '道教']},
				{char: "䷝", name: "六十四卦·离卦", ename: "Li Hexagram", tags: ['易经', '道教']},
				{char: "䷞", name: "六十四卦·咸卦", ename: "Xian Hexagram", tags: ['易经', '道教']},
				{char: "䷟", name: "六十四卦·恒卦", ename: "Heng Hexagram", tags: ['易经', '道教']},
				{char: "䷠", name: "六十四卦·遁卦", ename: "Dun Hexagram", tags: ['易经', '道教']},
				{char: "䷡", name: "六十四卦·大壮卦", ename: "Da Zhuang Hexagram", tags: ['易经', '道教']},
				{char: "䷢", name: "六十四卦·晋卦", ename: "Jin Hexagram", tags: ['易经', '道教']},
				{char: "䷣", name: "六十四卦·明夷卦", ename: "Ming Yi Hexagram", tags: ['易经', '道教']},
				{char: "䷤", name: "六十四卦·家人卦", ename: "Jia Ren Hexagram", tags: ['易经', '道教']},
				{char: "䷥", name: "六十四卦·睽卦", ename: "Kui Hexagram", tags: ['易经', '道教']},
				{char: "䷦", name: "六十四卦·蹇卦", ename: "Jian Hexagram", tags: ['易经', '道教']},
				{char: "䷧", name: "六十四卦·解卦", ename: "Jie Hexagram", tags: ['易经', '道教']},
				{char: "䷨", name: "六十四卦·损卦", ename: "Sun Hexagram", tags: ['易经', '道教']},
				{char: "䷩", name: "六十四卦·益卦", ename: "Yi Hexagram", tags: ['易经', '道教']},
				{char: "䷪", name: "六十四卦·夬卦", ename: "Guai Hexagram", tags: ['易经', '道教']},
				{char: "䷫", name: "六十四卦·姤卦", ename: "Gou Hexagram", tags: ['易经', '道教']},
				{char: "䷬", name: "六十四卦·萃卦", ename: "Cui Hexagram", tags: ['易经', '道教']},
				{char: "䷭", name: "六十四卦·升卦", ename: "Sheng Hexagram", tags: ['易经', '道教']},
				{char: "䷮", name: "六十四卦·困卦", ename: "Kun Hexagram", tags: ['易经', '道教']},
				{char: "䷯", name: "六十四卦·井卦", ename: "Jing Hexagram", tags: ['易经', '道教']},
				{char: "䷰", name: "六十四卦·革卦", ename: "Ge Hexagram", tags: ['易经', '道教']},
				{char: "䷱", name: "六十四卦·鼎卦", ename: "Ding Hexagram", tags: ['易经', '道教']},
				{char: "䷲", name: "六十四卦·震卦", ename: "Zhen Hexagram", tags: ['易经', '道教']},
				{char: "䷳", name: "六十四卦·艮卦", ename: "Gen Hexagram", tags: ['易经', '道教']},
				{char: "䷴", name: "六十四卦·渐卦", ename: "Jian Hexagram", tags: ['易经', '道教']},
				{char: "䷵", name: "六十四卦·归妹卦", ename: "Gui Mei Hexagram", tags: ['易经', '道教']},
				{char: "䷶", name: "六十四卦·丰卦", ename: "Feng Hexagram", tags: ['易经', '道教']},
				{char: "䷷", name: "六十四卦·旅卦", ename: "Lv Hexagram", tags: ['易经', '道教']},
				{char: "䷸", name: "六十四卦·巽卦", ename: "Xun Hexagram", tags: ['易经', '道教']},
				{char: "䷹", name: "六十四卦·兑卦", ename: "Dui Hexagram", tags: ['易经', '道教']},
				{char: "䷺", name: "六十四卦·涣卦", ename: "Huan Hexagram", tags: ['易经', '道教']},
				{char: "䷻", name: "六十四卦·节卦", ename: "Jie Hexagram", tags: ['易经', '道教']},
				{char: "䷼", name: "六十四卦·中孚卦", ename: "Zhong Fu Hexagram", tags: ['易经', '道教']},
				{char: "䷽", name: "六十四卦·小过卦", ename: "Xiao Guo Hexagram", tags: ['易经', '道教']},
				{char: "䷾", name: "六十四卦·既济卦", ename: "Ji Ji Hexagram", tags: ['易经', '道教']},
				{char: "䷿", name: "六十四卦·未济卦", ename: "Wei Ji Hexagram", tags: ['易经', '道教']}
			]
		},
		{
			name: '《太玄经》符号（八十一首）',
			symbols: [
				{char: "𝌀", name: "单爻（地）", ename: "Monogram for Earth"},
				{char: "𝌁", name: "双爻（天地区）", ename: "Digram for Heavenly Earth"},
				{char: "𝌂", name: "双爻（人地区）", ename: "Digram for Human Earth"},
				{char: "𝌃", name: "双爻（地天区）", ename: "Digram for Earthly Heaven"},
				{char: "𝌄", name: "双爻（地人区）", ename: "Digram for Earthly Human"},
				{char: "𝌅", name: "双爻（地区）", ename: "Digram for Earth"},

				{char: "𝌆", name: "八十一首·中", ename: "Tetragram for Centre"},
				{char: "𝌇", name: "八十一首·周", ename: "Tetragram for Full Circle"},
				{char: "𝌈", name: "八十一首·礥", ename: "Tetragram for Mired"},
				{char: "𝌉", name: "八十一首·闲/閑", ename: "Tetragram for Barrier"},
				{char: "𝌊", name: "八十一首·少", ename: "Tetragram for Keeping Small"},
				{char: "𝌋", name: "八十一首·戾", ename: "Tetragram for Contrariety"},
				{char: "𝌌", name: "八十一首·上", ename: "Tetragram for Ascent"},
				{char: "𝌍", name: "八十一首·干", ename: "Tetragram for Opposition"},
				{char: "𝌎", name: "八十一首·狩", ename: "Tetragram for Branching Out"},
				{char: "𝌏", name: "八十一首·羡", ename: "Tetragram for Defectiveness or Distortion"},
				{char: "𝌐", name: "八十一首·差", ename: "Tetragram for Divergence"},
				{char: "𝌑", name: "八十一首·重", ename: "Tetragram for Youthfulness"},
				{char: "𝌒", name: "八十一首·增", ename: "Tetragram for Increase"},
				{char: "𝌓", name: "八十一首·锐/銳", ename: "Tetragram for Penetration"},
				{char: "𝌔", name: "八十一首·达/達", ename: "Tetragram for Reach"},
				{char: "𝌕", name: "八十一首·交", ename: "Tetragram for Contact"},
				{char: "𝌖", name: "八十一首·耎/䎡", ename: "Tetragram for Holding Back"},
				{char: "𝌗", name: "八十一首·徯", ename: "Tetragram for Waiting"},
				{char: "𝌘", name: "八十一首·从/從", ename: "Tetragram for Following"},
				{char: "𝌙", name: "八十一首·进/進", ename: "Tetragram for Advance"},
				{char: "𝌚", name: "八十一首·释/釋", ename: "Tetragram for Release"},
				{char: "𝌛", name: "八十一首·格", ename: "Tetragram for Resistance"},
				{char: "𝌜", name: "八十一首·夷", ename: "Tetragram for Ease"},
				{char: "𝌝", name: "八十一首·乐/樂", ename: "Tetragram for Joy"},
				{char: "𝌞", name: "八十一首·争/爭", ename: "Tetragram for Contention"},
				{char: "𝌟", name: "八十一首·务/務", ename: "Tetragram for Endeavour"},
				{char: "𝌠", name: "八十一首·事", ename: "Tetragram for Duties"},
				{char: "𝌡", name: "八十一首·更", ename: "Tetragram for Change"},
				{char: "𝌢", name: "八十一首·断/斷", ename: "Tetragram for Decisiveness"},
				{char: "𝌣", name: "八十一首·榖", ename: "Tetragram for Bold Resolution"},
				{char: "𝌤", name: "八十一首·裝", ename: "Tetragram for Packing"},
				{char: "𝌥", name: "八十一首·众/眾", ename: "Tetragram for Legion"},
				{char: "𝌦", name: "八十一首·密", ename: "Tetragram for Closeness"},
				{char: "𝌧", name: "八十一首·亲/親", ename: "Tetragram for Kinship"},
				{char: "𝌨", name: "八十一首·敛/歛", ename: "Tetragram for Gathering"},
				{char: "𝌩", name: "八十一首·彊", ename: "Tetragram for Strength"},
				{char: "𝌪", name: "八十一首·晬", ename: "Tetragram for Purity"},
				{char: "𝌫", name: "八十一首·盛", ename: "Tetragram for Fullness"},
				{char: "𝌬", name: "八十一首·居", ename: "Tetragram for Residence"},
				{char: "𝌭", name: "八十一首·法", ename: "Tetragram for Law or Model"},
				{char: "𝌮", name: "八十一首·应/應", ename: "Tetragram for Response"},
				{char: "𝌯", name: "八十一首·迎", ename: "Tetragram for Meeting"},
				{char: "𝌰", name: "八十一首·遇", ename: "Tetragram for Encounter"},
				{char: "𝌱", name: "八十一首·灶/竈", ename: "Tetragram for Stove"},
				{char: "𝌲", name: "八十一首·大", ename: "Tetragram for Greatness"},
				{char: "𝌳", name: "八十一首·廓", ename: "Tetragram for Enlargement"},
				{char: "𝌴", name: "八十一首·文", ename: "Tetragram for Pattern"},
				{char: "𝌵", name: "八十一首·礼/禮", ename: "Tetragram for Ritual"},
				{char: "𝌶", name: "八十一首·逃", ename: "Tetragram for Flight"},
				{char: "𝌷", name: "八十一首·唐", ename: "Tetragram for Extravagance"},
				{char: "𝌸", name: "八十一首·常", ename: "Tetragram for Constancy"},
				{char: "𝌹", name: "八十一首·度", ename: "Tetragram for Measure"},
				{char: "𝌺", name: "八十一首·永", ename: "Tetragram for Eternity"},
				{char: "𝌻", name: "八十一首·昆", ename: "Tetragram for Unity"},
				{char: "𝌼", name: "八十一首·灭/滅", ename: "Tetragram for Decrease"},
				{char: "𝌽", name: "八十一首·唫", ename: "Tetragram for Stoppage"},
				{char: "𝌾", name: "八十一首·守", ename: "Tetragram for Guardedness"},
				{char: "𝌿", name: "八十一首·翕", ename: "Tetragram for Contraction"},
				{char: "𝍀", name: "八十一首·聚", ename: "Tetragram for Gathering"},
				{char: "𝍁", name: "八十一首·积/積", ename: "Tetragram for Accumulation"},
				{char: "𝍂", name: "八十一首·饰/飾", ename: "Tetragram for Embellishment"},
				{char: "𝍃", name: "八十一首·疑", ename: "Tetragram for Doubt"},
				{char: "𝍄", name: "八十一首·视/視", ename: "Tetragram for Watch"},
				{char: "𝍅", name: "八十一首·沈", ename: "Tetragram for Sinking"},
				{char: "𝍆", name: "八十一首·内/內", ename: "Tetragram for Inner"},
				{char: "𝍇", name: "八十一首·去", ename: "Tetragram for Departure"},
				{char: "𝍈", name: "八十一首·晦", ename: "Tetragram for Darkening"},
				{char: "𝍉", name: "八十一首·瞢", ename: "Tetragram for Dimming"},
				{char: "𝍊", name: "八十一首·穷/窮", ename: "Tetragram for Exhaustion"},
				{char: "𝍋", name: "八十一首·割", ename: "Tetragram for Severance"},
				{char: "𝍌", name: "八十一首·止", ename: "Tetragram for Stoppage"},
				{char: "𝍍", name: "八十一首·坚/堅", ename: "Tetragram for Hardness"},
				{char: "𝍎", name: "八十一首·成", ename: "Tetragram for Completion"},
				{char: "𝍏", name: "八十一首·阙/闕", ename: "Tetragram for Closure"},
				{char: "𝍐", name: "八十一首·矢", ename: "Tetragram for Failure"},
				{char: "𝍑", name: "八十一首·剧/劇", ename: "Tetragram for Aggravation"},
				{char: "𝍒", name: "八十一首·驯/馴", ename: "Tetragram for Compliance"},
				{char: "𝍓", name: "八十一首·将/將", ename: "Tetragram for On the Verge"},
				{char: "𝍔", name: "八十一首·难/難", ename: "Tetragram for Difficulties"},
				{char: "𝍕", name: "八十一首·勤/勤", ename: "Tetragram for Labouring"},
				{char: "𝍖", name: "八十一首·养/養", ename: "Tetragram for Fostering"}
			]
		},
		{
			name: '其他',
			symbols: [
				{char: "☸", name: "佛教法轮", ename: "WHEEL OF DHARMA", tags: []},
				{char: "☥", name: "生命之符", ename: "Ankh", tags: ['安卡', '安克', '埃及']},
				{char: "☤", name: "商神杖", ename: "Caduceus", tags: ['墨丘利的节杖', '古希腊']},

				{char: "☓", name: "圣安德鲁十字", ename: "St Andrew's Cross", tags: ['基督教']},
				{char: "☦", name: "东正教十字", ename: "Orthodox Cross", tags: ['基督教']},
				{char: "☧", name: "基督符号", ename: "Chi Rho", tags: ['基督教']},
				{char: "☨", name: "洛林十字", ename: "Cross of Lorraine", tags: ['基督教', '法国']},
				{char: "☩", name: "耶路撒冷十字", ename: "Cross of Jerusalem", tags: ['基督教']},
				{char: "♰", name: "西叙利亚十字", ename: "West Syriac Cross", tags: ['十字', '基督教']},
				{char: "♱", name: "东叙利亚十字", ename: "East Syriac Cross", tags: ['十字', '基督教']},
				{char: "⛝", name: "交叉十字", ename: "SQUARED SALTIRE", tags: ["符号", "宗教"]},

				{char: "☪", name: "星月", ename: "Star and Crescent", tags: ['伊斯兰教']},
				{char: "☫", name: "法拉瓦哈", ename: "Faravahar", tags: ['伊朗']},

				{char: "☬", name: "坎达（锡克教符号）", ename: "Khanda", tags: ['印度']},
				{char: "☭", name: "镰刀锤子", ename: "Hammer and Sickle", tags: ['共产党', '苏维埃', '苏联']},

				{char: "⛤", name: "五角星", ename: "Pentagram", tags: ['五角星', '魔法']},
				{char: "⛥", name: "右手交织五角星", ename: "Right-Handed Interlaced Pentagram", tags: ['神秘学', '炼金术']},
				{char: "⛦", name: "左手交织五角星", ename: "Left-Handed Interlaced Pentagram", tags: ['基督教', '东正教']},
				{char: "⛧", name: "倒五角星", ename: "Inverted Pentagram", tags: ['倒置', '基督教']},
				{char: "⛨", name: "盾牌黑十字", ename: "Black Cross On Shield", tags: ['盾牌']},
				{char: "⛩", name: "神道教神社", ename: "Shinto Shrine", tags: []},
				{char: "⛪", name: "教堂", ename: "Church", tags: []},

				{char: "⚸", name: "黑月莉莉丝", ename: "Black Moon Lilith", tags: ['黑月', '占星术']},
				{char: "⚹", name: "六分相", ename: "Sextile", tags: ['六分相', '占星术']},
				{char: "⚺", name: "十二分相", ename: "Semisextile", tags: ['半六分相', '占星术']},
				{char: "⚻", name: "梅花相", ename: "Quincunx", tags: ['梅花相', '占星术']},
				{char: "⚼", name: "倍八分相", ename: "Sesquiquadrate", tags: ['倍半四分相', '占星术']}
			]
		}
	]
};