const data = {
	name: "数学",
	groups: [
		{
			name: "数字",
			symbols: [
				{char: "①", name: "带圈数字一", ename: "Circled Digit One"},
				{char: "②", name: "带圈数字二", ename: "Circled Digit Two"},
				{char: "③", name: "带圈数字三", ename: "Circled Digit Three"},
				{char: "④", name: "带圈数字四", ename: "Circled Digit Four"},
				{char: "⑤", name: "带圈数字五", ename: "Circled Digit Five"},
				{char: "⑥", name: "带圈数字六", ename: "Circled Digit Six"},
				{char: "⑦", name: "带圈数字七", ename: "Circled Digit Seven"},
				{char: "⑧", name: "带圈数字八", ename: "Circled Digit Eight"},
				{char: "⑨", name: "带圈数字九", ename: "Circled Digit Nine"},
				{char: "⑩", name: "带圈数字十", ename: "Circled Number Ten"},
				{char: "Ⅰ", name: "罗马数字一", ename: "Roman Numeral One"},
				{char: "Ⅱ", name: "罗马数字二", ename: "Roman Numeral Two"},
				{char: "Ⅲ", name: "罗马数字三", ename: "Roman Numeral Three"},
				{char: "Ⅳ", name: "罗马数字四", ename: "Roman Numeral Four"},
				{char: "Ⅴ", name: "罗马数字五", ename: "Roman Numeral Five"},
				{char: "Ⅵ", name: "罗马数字六", ename: "Roman Numeral Six"},
				{char: "Ⅶ", name: "罗马数字七", ename: "Roman Numeral Seven"},
				{char: "Ⅷ", name: "罗马数字八", ename: "Roman Numeral Eight"},
				{char: "Ⅸ", name: "罗马数字九", ename: "Roman Numeral Nine"},
				{char: "Ⅹ", name: "罗马数字十", ename: "Roman Numeral Ten"},
				{char: "Ⅺ", name: "罗马数字十一", ename: "Roman Numeral Eleven"},
				{char: "Ⅻ", name: "罗马数字十二", ename: "Roman Numeral Twelve"}
			]
		},
		{
			name: '运算符、操作符、比较符',
			symbols: [
				{char: "+", name: "加号", ename: "Plus Sign"},
				{char: "-", name: "减号", ename: "Minus Sign"},
				{char: "×", name: "乘号", ename: "Multiplication Sign"},
				{char: "÷", name: "除号", ename: "Division Sign"},
				{char: "±", name: "正负号", ename: "Plus-Minus Sign"},
				{char: "≠", name: "不等于号", ename: "Not Equal To"},
				{char: "≈", name: "约等于号", ename: "Almost Equal To"},
				{char: "≅", name: "全等于号", ename: "Congruent To"},
				{char: "≡", name: "恒等于号", ename: "Identical To"},
				{char: "∝", name: "正比于", ename: "Proportional To"},
				{char: "≤", name: "小于等于号", ename: "Less-Than or Equal To"},
				{char: "≥", name: "大于等于号", ename: "Greater-Than or Equal To"},
				{char: "∞", name: "无穷大", ename: "Infinity"},
				{char: "∫", name: "积分", ename: "Integral"},
				{char: "∑", name: "求和", ename: "N-Ary Summation"},
				{char: "∏", name: "求积", ename: "N-Ary Product"},
				{char: "√", name: "平方根", ename: "Square Root"},
				{char: "∛", name: "立方根", ename: "Cube Root"},
				{char: "∜", name: "四次方根", ename: "Fourth Root"},
				{char: "∠", name: "角", ename: "Angle"},
				{char: "⊥", name: "垂直", ename: "Up Tack"},
				{char: "∥", name: "平行", ename: "Parallel To"},
				{char: "∧", name: "逻辑与", ename: "Logical And"},
				{char: "∨", name: "逻辑或", ename: "Logical Or"},
				{char: "∩", name: "交集", ename: "Intersection"},
				{char: "∪", name: "并集", ename: "Union"},
				{char: "∈", name: "属于", ename: "Element Of"},
				{char: "∉", name: "不属于", ename: "Not an Element Of"},
				{char: "⊂", name: "…的子集", ename: "Subset Of"},
				{char: "⊃", name: "…的超集", ename: "Superset Of"},
				{char: "⊆", name: "…的子集或等于", ename: "Subset of or Equal To"},
				{char: "⊇", name: "…的超集或等于", ename: "Superset of or Equal To"},
				{char: "∅", name: "空集", ename: "Empty Set"},
				{char: "∀", name: "任意", ename: "For All"},
				{char: "∃", name: "存在", ename: "There Exists"},
				{char: "∴", name: "所以", ename: "Therefore"},
				{char: "∵", name: "因为", ename: "Because"}
			]
		},
		{
			name: '几何图形',
			symbols: [
				{char: "⚪", name: "白圆", ename: "Medium White Circle", tags: ['圆形', '白色']},
				{char: "⚫", name: "黑圆", ename: "Medium Black Circle", tags: ['圆形', '黑色']},
				{char: "⛛", name: "重白下指三角", ename: "Heavy White Down-Pointing Triangle", tags: ['指向']},
				{char: "⚆", name: "白圆右点", ename: "White Circle with Dot Right", tags: ['圆形', '点']},
				{char: "⚇", name: "白圆双点", ename: "White Circle with Two Dots", tags: ['圆形', '点']},
				{char: "⚈", name: "黑圆右点", ename: "Black Circle with White Dot Right", tags: ['圆形', '点']},
				{char: "⚉", name: "黑圆双点", ename: "Black Circle with Two White Dots", tags: ['圆形', '点']},
				{char: "⛋", name: "正方形内接菱形", ename: "WHITE DIAMOND IN SQUARE", tags: ['圆形', '点']},
				{char: "⛶", name: "四角方框", ename: "SQUARE FOUR CORNERS", tags: ["符号", "几何"]},
			]
		}
	]
};